export type PathExercise = {
  id: string;
  kind: "lesson" | "puzzle" | "calculation" | "endgame" | "review";
  fr: { title: string; goal: string };
  en: { title: string; goal: string };
};

export type PathLevel = {
  id: number;
  fr: { title: string; summary: string; milestone: string };
  en: { title: string; summary: string; milestone: string };
  prerequisite: number | null;
  estimatedLessons: number;
  exercises: PathExercise[];
};

const exercise = (id: string, kind: PathExercise["kind"], frTitle: string, frGoal: string, enTitle: string, enGoal: string): PathExercise => ({
  id,
  kind,
  fr: { title: frTitle, goal: frGoal },
  en: { title: enTitle, goal: enGoal },
});

/**
 * The roadmap is deliberately represented as content, not progress state.
 * Unlocking is calculated from completed lessons so this catalogue stays
 * safe to evolve without rewriting a user's history.
 */
export const learningPath: PathLevel[] = [
  { id: 0, fr: { title: "Comprendre le jeu", summary: "Le matériel, les pièces, les règles et une première partie complète contre un adversaire accessible.", milestone: "Gagner une partie complète sans consulter les règles." }, en: { title: "Understand the game", summary: "The equipment, pieces, rules and a first complete game against an accessible opponent.", milestone: "Win a complete game without checking the rules." }, prerequisite: null, estimatedLessons: 6, exercises: [exercise("0-board", "lesson", "Comprendre le matériel", "Lire l’échiquier, les pièces, les valeurs et l’Elo.", "Understand the equipment", "Read the board, pieces, values and Elo."), exercise("0-pieces", "lesson", "Déplacer les pièces", "Exercer le mouvement de chaque pièce.", "Move the pieces", "Practice each piece’s movement."), exercise("0-capture", "lesson", "Prendre et promouvoir", "Réaliser une prise et transformer un pion.", "Capture and promote", "Make a capture and transform a pawn."), exercise("0-checkmate", "puzzle", "Échec et mat", "Donner échec et reconnaître le mat.", "Check and checkmate", "Give check and recognize mate."), exercise("0-special", "lesson", "Coups spéciaux et nulles", "Roquer, prendre en passant et reconnaître quatre nulles.", "Special moves and draws", "Castle, play en passant and recognize four draws."), exercise("0-complete", "review", "Gagner une partie complète", "Jouer contre un ordinateur pour valider le niveau.", "Win a complete game", "Play a computer game to validate the level.")] },
  { id: 1, fr: { title: "Les principes fondamentaux", summary: "Comprendre l’objectif, développer ses pièces et mettre le roi à l’abri.", milestone: "Avant chaque coup, demander ce que veut faire l’adversaire." }, en: { title: "Fundamental principles", summary: "Understand the goal, develop pieces and keep the king safe.", milestone: "Before every move, ask what the opponent wants." }, prerequisite: 0, estimatedLessons: 6, exercises: [exercise("1-center", "lesson", "Prendre le centre", "Jouer e4 ou d4 pour ouvrir des lignes et gagner de l’espace.", "Claim the center", "Play e4 or d4 to open lines and gain space."), exercise("1-development", "lesson", "Développer avec intention", "Sortir les pièces mineures sans perdre de temps.", "Develop with purpose", "Bring out minor pieces without losing time."), exercise("1-safety", "puzzle", "Le roi à l’abri", "Préparer et exécuter le roque au bon moment.", "Keep the king safe", "Prepare and castle at the right moment.")] },
  { id: 2, fr: { title: "La vision tactique", summary: "Reconnaître les motifs qui gagnent du matériel ou créent une menace immédiate.", milestone: "Voir une attaque double avant qu’elle n’arrive." }, en: { title: "Tactical vision", summary: "Recognize patterns that win material or create an immediate threat.", milestone: "Spot a double attack before it happens." }, prerequisite: 1, estimatedLessons: 8, exercises: [exercise("2-fork", "puzzle", "Fourchettes et attaques doubles", "Créer deux menaces avec un seul coup.", "Forks and double attacks", "Create two threats with one move."), exercise("2-pin", "puzzle", "Clouage et enfilade", "Exploiter une pièce qui ne peut pas bouger.", "Pins and skewers", "Exploit a piece that cannot move."), exercise("2-defender", "puzzle", "Éliminer le défenseur", "Retirer la pièce qui protège le motif tactique.", "Remove the defender", "Remove the piece protecting the tactic.")] },
  { id: 3, fr: { title: "Calculer les variantes", summary: "Organiser sa réflexion avec la méthode Échecs : échecs, prises, menaces.", milestone: "Comparer deux variantes sans déplacer les pièces." }, en: { title: "Calculate variations", summary: "Organize your thinking with checks, captures and threats.", milestone: "Compare two variations without moving the pieces." }, prerequisite: 2, estimatedLessons: 7, exercises: [exercise("3-candidates", "calculation", "Les coups candidats", "Lister les coups forcing avant de choisir.", "Candidate moves", "List forcing moves before choosing."), exercise("3-cct", "calculation", "Échecs, prises, menaces", "Calculer la réponse adverse la plus forte.", "Checks, captures, threats", "Calculate the opponent’s strongest reply."), exercise("3-visual", "calculation", "Visualiser trois coups", "Reconstituer mentalement une position après une variante.", "Visualize three moves", "Rebuild a position after a variation.")] },
  { id: 4, fr: { title: "Les finales fondamentales", summary: "Apprendre à gagner avec peu de matériel : roi, pion, tour et opposition.", milestone: "Convertir un pion passé en promotion." }, en: { title: "Essential endgames", summary: "Learn to win with little material: king, pawn, rook and opposition.", milestone: "Turn a passed pawn into a promotion." }, prerequisite: 3, estimatedLessons: 8, exercises: [exercise("4-opposition", "endgame", "L’opposition", "Gagner la case clé avec les rois.", "Opposition", "Win the key square with the kings."), exercise("4-square", "endgame", "La règle du carré", "Savoir si le roi rejoint un pion passé.", "The square rule", "Know whether the king catches a passed pawn."), exercise("4-rook", "endgame", "Tour contre roi", "Donner mat avec une tour et son roi.", "Rook versus king", "Checkmate with a rook and king.")] },
  { id: 5, fr: { title: "Comprendre la position", summary: "Lire les structures de pions et reconnaître les cases fortes ou faibles.", milestone: "Identifier la faiblesse qui guide le plan." }, en: { title: "Understand the position", summary: "Read pawn structures and recognize strong or weak squares.", milestone: "Identify the weakness that guides the plan." }, prerequisite: 4, estimatedLessons: 7, exercises: [exercise("5-pawns", "lesson", "Structures de pions", "Comparer pions isolés, doublés et passés.", "Pawn structures", "Compare isolated, doubled and passed pawns."), exercise("5-squares", "puzzle", "Les cases fortes", "Installer une pièce sur un avant-poste.", "Strong squares", "Place a piece on an outpost."), exercise("5-plan", "calculation", "Du constat au plan", "Relier une faiblesse à une action concrète.", "From evaluation to plan", "Turn a weakness into a concrete plan.")] },
  { id: 6, fr: { title: "Comprendre les pièces", summary: "Améliorer le cavalier, le fou, les tours, la dame et le roi selon la position.", milestone: "Améliorer sa pire pièce avant de chercher une combinaison." }, en: { title: "Understand the pieces", summary: "Improve knights, bishops, rooks, queens and kings according to the position.", milestone: "Improve your worst piece before seeking a combination." }, prerequisite: 5, estimatedLessons: 8, exercises: [exercise("6-knight", "lesson", "Le bon cavalier", "Trouver une case centrale et un avant-poste.", "The good knight", "Find a central square and an outpost."), exercise("6-bishop", "lesson", "Le bon fou", "Ouvrir les diagonales et comprendre le mauvais fou.", "The good bishop", "Open diagonals and understand the bad bishop."), exercise("6-rooks", "puzzle", "La tour active", "Occuper une colonne ouverte ou la septième rangée.", "The active rook", "Occupy an open file or the seventh rank.")] },
  { id: 7, fr: { title: "La stratégie positionnelle", summary: "Évaluer une position, choisir un plan et transformer un avantage.", milestone: "Formuler un plan en une phrase avant de jouer." }, en: { title: "Positional strategy", summary: "Evaluate a position, choose a plan and convert an advantage.", milestone: "State a plan in one sentence before moving." }, prerequisite: 6, estimatedLessons: 8, exercises: [exercise("7-eval", "calculation", "Évaluer sans moteur", "Comparer matériel, activité, roi, espace et structure.", "Evaluate without an engine", "Compare material, activity, king safety, space and structure."), exercise("7-worst", "lesson", "La pire pièce", "Trouver l’amélioration la plus utile.", "The worst piece", "Find the most useful improvement."), exercise("7-convert", "review", "Transformer l’avantage", "Échanger au bon moment et entrer dans une finale favorable.", "Convert the advantage", "Trade at the right moment and enter a favorable endgame.")] },
  { id: 8, fr: { title: "Attaquer le roi", summary: "Construire une attaque avec les lignes, les pièces et les motifs de mat.", milestone: "Reconnaître quand ouvrir une ligne contre le roi." }, en: { title: "Attack the king", summary: "Build an attack with open lines, coordinated pieces and mating patterns.", milestone: "Recognize when to open a line against the king." }, prerequisite: 7, estimatedLessons: 8, exercises: [exercise("8-lines", "puzzle", "Ouvrir les lignes", "Sacrifier ou pousser un pion pour créer une attaque.", "Open the lines", "Sacrifice or push a pawn to create an attack."), exercise("8-mates", "puzzle", "Motifs de mat", "Repérer mat du couloir, batterie et filet de mat.", "Mating patterns", "Spot back-rank mates, batteries and mating nets."), exercise("8-attack", "calculation", "La coordination", "Calculer avec dame, tour et fou autour du roi.", "Coordination", "Calculate with queen, rook and bishop around the king.")] },
  { id: 9, fr: { title: "Les ouvertures comprises", summary: "Construire un répertoire cohérent à partir des principes, pas de la mémoire brute.", milestone: "Expliquer l’idée d’une ouverture avant ses coups théoriques." }, en: { title: "Understand openings", summary: "Build a coherent repertoire from principles, not raw memorization.", milestone: "Explain an opening’s idea before its theory." }, prerequisite: 8, estimatedLessons: 8, exercises: [exercise("9-e4", "lesson", "Les familles après e4", "Comprendre l’Italienne, l’Espagnole et les défenses principales.", "Families after e4", "Understand the Italian, Spanish and main defenses."), exercise("9-d4", "lesson", "Les familles après d4", "Comparer gambit dame, slave et indiennes.", "Families after d4", "Compare the Queen’s Gambit, Slav and Indian systems."), exercise("9-repertoire", "review", "Votre répertoire", "Choisir une réponse principale et une secondaire.", "Your repertoire", "Choose a main and a secondary response.")] },
  { id: 10, fr: { title: "Le milieu de jeu", summary: "Reconnaître les types de positions et les plans qui en découlent.", milestone: "Nommer la structure avant de chercher un coup." }, en: { title: "The middlegame", summary: "Recognize position types and the plans that follow from them.", milestone: "Name the structure before searching for a move." }, prerequisite: 9, estimatedLessons: 7, exercises: [exercise("10-types", "lesson", "Ouverte ou fermée", "Adapter son plan au centre et aux lignes disponibles.", "Open or closed", "Adapt your plan to the center and available lines."), exercise("10-break", "puzzle", "La rupture de pions", "Choisir la poussée qui libère ses pièces.", "The pawn break", "Choose the pawn break that frees your pieces."), exercise("10-wings", "calculation", "Jouer sur deux ailes", "Créer une seconde faiblesse sans perdre le tempo.", "Play on both wings", "Create a second weakness without losing time.")] },
  { id: 11, fr: { title: "Le jeu dynamique", summary: "Comprendre l’initiative, la compensation et la défense active.", milestone: "Préférer une menace active à une défense passive." }, en: { title: "Dynamic play", summary: "Understand initiative, compensation and active defense.", milestone: "Prefer an active threat to passive defense." }, prerequisite: 10, estimatedLessons: 6, exercises: [exercise("11-initiative", "calculation", "Gagner un tempo", "Créer une menace qui oblige une réponse.", "Gain a tempo", "Create a threat that forces a reply."), exercise("11-compensation", "puzzle", "La compensation", "Évaluer activité contre matériel.", "Compensation", "Evaluate activity against material."), exercise("11-counter", "puzzle", "Contre-attaquer", "Défendre en créant une menace plus forte.", "Counterattack", "Defend by creating a stronger threat.")] },
  { id: 12, fr: { title: "Les techniques avancées", summary: "Maîtriser les échanges, la tension et la valeur d’un tempo.", milestone: "Expliquer pourquoi un échange est favorable." }, en: { title: "Advanced techniques", summary: "Master exchanges, tension and the value of a tempo.", milestone: "Explain why an exchange is favorable." }, prerequisite: 11, estimatedLessons: 6, exercises: [exercise("12-trades", "review", "Échanger ou garder", "Choisir la bonne pièce à échanger.", "Trade or keep", "Choose the right piece to exchange."), exercise("12-tension", "calculation", "Maintenir la tension", "Ne pas prendre quand l’ouverture vous défavorise.", "Keep the tension", "Do not capture when opening the position hurts you."), exercise("12-tempo", "puzzle", "Le tempo tactique", "Gagner un temps utile sur une pièce.", "The tactical tempo", "Gain a useful tempo on a piece.")] },
  { id: 13, fr: { title: "Le calcul avancé", summary: "Construire un arbre de variantes et penser de façon prophylactique.", milestone: "Anticiper le plan adverse avant de jouer le sien." }, en: { title: "Advanced calculation", summary: "Build a variation tree and think prophylactically.", milestone: "Anticipate the opponent’s plan before your own." }, prerequisite: 12, estimatedLessons: 7, exercises: [exercise("13-tree", "calculation", "L’arbre de variantes", "Comparer plusieurs réponses adverses.", "The variation tree", "Compare several opponent replies."), exercise("13-quiet", "calculation", "Le coup calme", "Calculer une amélioration sans forcing.", "The quiet move", "Calculate a non-forcing improvement."), exercise("13-prophylaxis", "puzzle", "Le coup préventif", "Empêcher le plan adverse le plus dangereux.", "The preventive move", "Prevent the opponent’s most dangerous plan.")] },
  { id: 14, fr: { title: "La psychologie pratique", summary: "Gérer son temps, ses émotions et la discipline de décision.", milestone: "Prendre son temps dans les positions critiques." }, en: { title: "Practical psychology", summary: "Manage time, emotions and decision-making discipline.", milestone: "Take your time in critical positions." }, prerequisite: 13, estimatedLessons: 5, exercises: [exercise("14-clock", "review", "La pendule intérieure", "Identifier les positions qui méritent une pause.", "The inner clock", "Identify positions that deserve a pause."), exercise("14-discipline", "review", "Jouer simple", "Éviter le sacrifice décoratif et le coup naturel.", "Play simply", "Avoid decorative sacrifices and automatic moves."), exercise("14-defense", "calculation", "Défendre une position difficile", "Rester actif même avec moins d’espace.", "Defend a difficult position", "Stay active with less space.")] },
  { id: 15, fr: { title: "Analyser ses parties", summary: "Utiliser d’abord sa réflexion, puis Stockfish, pour classer et comprendre ses erreurs.", milestone: "Transformer une erreur en principe à retenir." }, en: { title: "Analyze your games", summary: "Use your own thinking first, then Stockfish, to classify and understand mistakes.", milestone: "Turn one mistake into a principle to remember." }, prerequisite: 14, estimatedLessons: 6, exercises: [exercise("15-human", "review", "Analyse sans moteur", "Repérer le moment où le plan a changé.", "Human-first review", "Find the moment when the plan changed."), exercise("15-engine", "review", "Le moteur explique", "Comparer le coup joué et le meilleur coup.", "Let the engine explain", "Compare the played move and the best move."), exercise("15-pattern", "review", "Classer l’erreur", "Choisir ouverture, tactique, calcul, plan ou finale.", "Classify the mistake", "Choose opening, tactic, calculation, plan or endgame.")] },
  { id: 16, fr: { title: "Les parties des grands joueurs", summary: "Rejouer les parties modèles et chercher son propre coup avant la suite.", milestone: "Comprendre une décision critique d’un grand joueur." }, en: { title: "Master games", summary: "Replay model games and find your own move before seeing the continuation.", milestone: "Understand a master’s critical decision." }, prerequisite: 15, estimatedLessons: 6, exercises: [exercise("16-morphy", "review", "L’attaque de Morphy", "Observer développement et lignes ouvertes.", "Morphy’s attack", "Observe development and open lines."), exercise("16-capablanca", "review", "La simplicité de Capablanca", "Voir comment une petite amélioration devient un plan.", "Capablanca’s simplicity", "See how a small improvement becomes a plan."), exercise("16-modern", "review", "Une partie moderne", "Comparer la décision humaine et l’analyse moteur.", "A modern game", "Compare human decisions with engine analysis.")] },
  { id: 17, fr: { title: "Les finales avancées", summary: "Approfondir les finales de tours, de dames et les finales de pièces contre pions.", milestone: "Convertir une finale technique sans précipitation." }, en: { title: "Advanced endgames", summary: "Deepen rook, queen and minor-piece endings against pawns.", milestone: "Convert a technical ending without rushing." }, prerequisite: 16, estimatedLessons: 8, exercises: [exercise("17-lucena", "endgame", "Le pont de Lucena", "Construire le pont avec la tour.", "The Lucena bridge", "Build the bridge with the rook."), exercise("17-philidor", "endgame", "La défense de Philidor", "Tenir une finale de tour avec la défense active.", "The Philidor defense", "Hold a rook ending with active defense."), exercise("17-queen", "endgame", "Dame et pions", "Éviter les échecs perpétuels et promouvoir.", "Queen and pawns", "Avoid perpetual check and promote.")] },
];

export function isLevelUnlocked(level: PathLevel, completedLevels: Set<string>) {
  if (level.prerequisite === null) return true;
  return completedLevels.has(`level-${level.prerequisite}`);
}
