import type { BilingualText, LessonDefinition, LessonStep, TheorySection } from "./levelZeroLessons";
import { correctedTacticalSteps } from "./correctedTacticalSteps";

type StepSpec = [string, string, string, string, string, string, string, string];
type TopicSpec = {
  key: string;
  number: string;
  title: BilingualText;
  kicker: BilingualText;
  headline: BilingualText;
  objective: BilingualText;
  reflection: BilingualText;
  solution: BilingualText;
  sections: TheorySection[];
  points: Array<{ title: BilingualText; text: BilingualText }>;
  steps: StepSpec[];
};

const text = (fr: string, en: string): BilingualText => ({ fr, en });
const section = (titleFr: string, titleEn: string, textFr: string, textEn: string, items?: Array<[string, string, string, string]>): TheorySection => ({
  title: text(titleFr, titleEn),
  text: text(textFr, textEn),
  items: items?.map(([labelFr, labelEn, itemFr, itemEn]) => ({ label: text(labelFr, labelEn), text: text(itemFr, itemEn) })),
});
const step = ([positionFen, from, to, san, answerFr, answerEn, ideaFr, ideaEn]: StepSpec): LessonStep => ({
  positionFen,
  from,
  to,
  san,
  answer: text(answerFr, answerEn),
  idea: text(ideaFr, ideaEn),
});

const topic = (spec: TopicSpec): LessonDefinition => ({
  key: spec.key,
  number: spec.number,
  mode: "guided",
  title: spec.title,
  kicker: spec.kicker,
  headline: spec.headline,
  objective: spec.objective,
  reflection: spec.reflection,
  solution: spec.solution,
  startingFen: spec.steps[0][0],
  steps: spec.steps.map(step),
  keyPoints: spec.points,
  theorySections: spec.sections,
  drawPositions: [],
});

const tactical = (number: string, title: BilingualText, headline: BilingualText, objective: BilingualText, reflection: BilingualText, solution: BilingualText, sections: TheorySection[], points: Array<{ title: BilingualText; text: BilingualText }>, steps: StepSpec[]): TopicSpec => ({
  key: number,
  number: number.padStart(2, "0"),
  title,
  kicker: text("Niveau 2 · Vision tactique", "Level 2 · Tactical vision"),
  headline,
  objective,
  reflection,
  solution,
  sections,
  points,
  steps,
});

export const levelTwoLessons: Record<string, LessonDefinition> = {
  "13": topic(tactical(
    "13", text("L’attaque double", "The double attack"), text("Un coup, deux problèmes à résoudre.", "One move, two problems to solve."), text("Reconnaître une attaque double : une seule pièce crée simultanément deux cibles ou deux menaces indépendantes.", "Recognize a double attack: one piece creates two separate targets or threats at the same time."), text("Quelles sont les deux conséquences concrètes de mon coup ?", "What are the two concrete consequences of my move?"), text("Une attaque double n’est pas seulement une attaque de pièce : elle gagne sa force parce que l’adversaire ne peut pas répondre efficacement aux deux problèmes.", "A double attack is not just a piece attack: it is powerful because the opponent cannot answer both problems efficiently."), [
      section("Définition", "Definition", "Une attaque double apparaît lorsqu’un même coup attaque au moins deux éléments importants : roi, dame, tour, pièce non protégée ou case de promotion. Elle peut être créée par un cavalier, une dame, une tour, un fou ou même un pion.", "A double attack appears when one move attacks at least two important elements: king, queen, rook, loose piece or promotion square. It can be created by a knight, queen, rook, bishop or even a pawn.", [["Cibles", "Targets", "Deux cibles doivent être réellement importantes et difficiles à sauver ensemble.", "Both targets must be genuinely important and difficult to save together."]]),
      section("Mécanisme", "Mechanism", "Le coup gagnant change la géométrie de la position. Il peut donner échec tout en attaquant une pièce, ou attaquer deux pièces en même temps sans échec.", "The winning move changes the geometry of the position. It may give check while attacking a piece, or attack two pieces at once without check.", [["Priorité", "Priority", "Une attaque contre le roi oblige à répondre immédiatement ; la seconde cible sera souvent récupérée ensuite.", "An attack on the king forces an immediate reply; the second target can often be collected afterward."]]),
      section("Méthode de détection", "Detection method", "Après avoir regardé les échecs, cherchez les coups qui attaquent deux pièces. Comptez ensuite les cases de fuite et les défenses : une double attaque n’est bonne que si la réponse adverse ne neutralise pas les deux menaces.", "After looking for checks, look for moves that attack two pieces. Then count escape squares and defenses: a double attack works only if the reply cannot neutralize both threats.", [["Question", "Question", "Après mon coup, combien de réponses forcées possède l’adversaire ?", "After my move, how many forced replies does the opponent have?"]]),
      section("Erreur fréquente", "Common mistake", "Attaquer deux pions sans gagner de temps ni améliorer sa position n’est pas forcément une combinaison. La valeur des cibles, la sécurité du roi et la possibilité de contre-attaque comptent.", "Attacking two pawns without gaining time or improving the position is not necessarily a combination. Target value, king safety and counterplay matter.", [["Transfert", "Transfer", "Dans une partie, annoncez mentalement les deux menaces avant de conclure que le coup est tactique.", "In a game, name both threats mentally before deciding that the move is tactical."]]),
    ], [
      { title: text("Deux cibles", "Two targets"), text: text("Un seul coup doit créer deux problèmes vérifiables.", "One move must create two verifiable problems.") },
      { title: text("Force", "Force"), text: text("L’échec donne souvent le tempo nécessaire pour gagner la seconde cible.", "Check often gives the tempo needed to win the second target.") },
      { title: text("Calcul", "Calculation"), text: text("Cherchez la meilleure réponse adverse aux deux menaces.", "Find the opponent’s best answer to both threats.") },
    ], [
      ["k7/8/2r5/8/2N5/8/8/4K3 w - - 0 1", "c4", "e5", "Ce5", "Attaquez le roi et la tour avec le cavalier.", "Attack the king and rook with the knight.", "Le cavalier b5 vise a7 et c7 : deux cibles naissent du même saut.", "The knight on b5 attacks a7 and c7: two targets arise from one jump."],
      ["7k/8/8/8/8/8/4Q3/4K3 w - - 0 1", "e2", "h5", "Dh5", "Créez deux menaces sur la cinquième rangée.", "Create two threats on the fifth rank.", "La dame combine attaque de ligne et pression sur les cases d’évasion.", "The queen combines a line attack with pressure on escape squares."],
      ["6k1/8/8/8/8/2B5/8/4K3 w - - 0 1", "c3", "f6", "Ff6", "Utilisez le fou pour viser deux diagonales critiques.", "Use the bishop to target two critical diagonals.", "Le fou déplace son attaque vers le roi et une case de promotion.", "The bishop redirects its attack toward the king and a promotion square."],
    ],
  )),
  "14": topic(tactical(
    "14", text("La fourchette", "The fork"), text("Le cavalier qui attaque là où l’on ne peut pas répondre.", "The knight that attacks where no single reply is enough."), text("Exploiter une fourchette, surtout de cavalier, et vérifier que les pièces attaquées ne peuvent pas être sauvées ensemble.", "Exploit a fork, especially a knight fork, and check that the attacked pieces cannot both be saved."), text("Quelle pièce peut atteindre une case qui attaque plusieurs cibles ?", "Which piece can reach a square that attacks several targets?"), text("La fourchette est une forme concrète d’attaque double : la pièce arrive sur une case qui attaque plusieurs cibles, souvent le roi et la dame.", "A fork is a concrete form of double attack: the piece reaches a square that attacks several targets, often the king and queen."), [
      section("Définition", "Definition", "Une fourchette est une attaque double ou multiple réalisée par une pièce, avec une image classique : le cavalier fourche roi et dame. Les pions, la dame et le roi peuvent aussi fourcher.", "A fork is a double or multiple attack made by a piece, with a classic image: a knight forking king and queen. Pawns, queens and kings can fork too.", [["Motif", "Pattern", "Cherchez une case centrale ou avancée qui donne plusieurs attaques de cavalier.", "Look for a central or advanced square that gives several knight attacks."]]),
      section("Mécanisme", "Mechanism", "Le cavalier est particulièrement dangereux car il attaque sans être gêné par les pièces intermédiaires et ses cases d’attaque sont difficiles à bloquer.", "The knight is especially dangerous because its attacks cannot be blocked and its target squares are hard to interpose against.", [["Échec", "Check", "Une fourchette avec échec force le roi à bouger avant que la seconde pièce soit sauvée.", "A fork with check forces the king to move before the second piece can be saved."]]),
      section("Méthode de détection", "Detection method", "Examinez les cases d’échec du cavalier, puis les cases qui attaquent la dame ou une tour. Vérifiez les prises possibles sur la case de fourchette avant de jouer.", "Examine the knight’s checking squares, then squares that attack the queen or rook. Check whether the fork square can be captured before playing.", [["Calcul", "Calculation", "Après la fuite du roi, quelle pièce prenez-vous et quelle défense reste possible ?", "After the king moves, which piece do you take and what defense remains?"]]),
      section("Erreur fréquente", "Common mistake", "Une fourchette apparente échoue si la pièce qui arrive est clouée, si la case est défendue par le roi ou si l’adversaire possède un échec plus fort.", "An apparent fork fails if the arriving piece is pinned, the square is defended by the king or the opponent has a stronger check.", [["Transfert", "Transfer", "Avant de compter le gain, vérifiez toujours la sécurité de la pièce qui fourche.", "Before counting the gain, always check the safety of the forking piece."]]),
    ], [
      { title: text("Case de fourchette", "Fork square"), text: text("La case d’arrivée est plus importante que le nom de la pièce.", "The destination square matters more than the piece’s name.") },
      { title: text("Roi d’abord", "King first"), text: text("Une fourchette avec échec donne le tempo décisif.", "A checking fork gives the decisive tempo.") },
      { title: text("Sécurité", "Safety"), text: text("Une pièce qui fourche doit survivre au premier échange.", "A forking piece must survive the first exchange.") },
    ], [
      ["k7/8/2q5/8/2N5/8/8/4K3 w - - 0 1", "c4", "e5", "Ce5", "Fourchez le roi et la dame.", "Fork the king and queen.", "Le cavalier b5 attaque a7 et c7 ; le roi doit répondre avant la dame.", "The knight on b5 attacks a7 and c7; the king must respond before the queen."],
      ["6k1/8/8/8/8/2N5/8/4K3 w - - 0 1", "c3", "d5", "Cd5", "Placez le cavalier sur une case de fourchette.", "Place the knight on a fork square.", "Depuis d5, le cavalier gagne des tempos contre les cases critiques autour du roi.", "From d5, the knight gains tempi against critical squares around the king."],
      ["7k/8/8/8/8/2N5/8/4K3 w - - 0 1", "c3", "e4", "Ce4", "Cherchez la fourchette avec échec.", "Look for the checking fork.", "L’échec réduit les réponses adverses et laisse le temps de prendre la seconde cible.", "Check reduces the opponent’s replies and leaves time to take the second target."],
    ],
  )),
  "15": topic(tactical(
    "15", text("Le clouage", "The pin"), text("Une pièce peut bouger, mais elle ne peut pas se permettre de le faire.", "A piece may be able to move, but cannot afford to do so."), text("Distinguer le clouage absolu du clouage relatif et exploiter la pièce qui protège une cible plus importante derrière elle.", "Distinguish an absolute pin from a relative pin and exploit the piece protecting a more important target behind it."), text("Que se trouve derrière la pièce attaquée et que perd-elle si elle bouge ?", "What is behind the attacked piece, and what does it lose if it moves?"), text("Un clouage immobilise une pièce par une conséquence : derrière elle se trouve le roi ou une cible de grande valeur.", "A pin restricts a piece through a consequence: behind it stands the king or a high-value target."), [
      section("Définition", "Definition", "Dans un clouage, une pièce se trouve alignée avec une cible plus importante. Le clouage est absolu si bouger expose le roi ; il est relatif si bouger perd la dame, la tour ou une autre pièce.", "In a pin, a piece is aligned with a more important target. The pin is absolute if moving exposes the king; relative if moving loses the queen, rook or another piece.", [["Ligne", "Line", "Les tours, fous et dames sont les pièces qui créent le plus souvent les clouages.", "Rooks, bishops and queens most often create pins."]]),
      section("Mécanisme", "Mechanism", "Le clouage n’est pas toujours un gain immédiat. Il peut empêcher une défense, fixer une faiblesse ou préparer une attaque sur la pièce clouée.", "A pin is not always an immediate win. It can stop a defense, fix a weakness or prepare an attack on the pinned piece.", [["Absolu", "Absolute", "Une pièce absolument clouée ne peut pas jouer légalement si elle découvre le roi.", "An absolutely pinned piece cannot legally move if it exposes the king."]]),
      section("Méthode de détection", "Detection method", "Cherchez les alignements roi–pièce–attaquant et cible de grande valeur–pièce–attaquant. Puis ajoutez un attaquant sur la pièce clouée ou attaquez la cible derrière elle.", "Look for king–piece–attacker and high-value target–piece–attacker alignments. Then add an attacker to the pinned piece or attack the target behind it.", [["Test", "Test", "Si la pièce clouée bouge, l’adversaire perd-il réellement quelque chose d’important ?", "If the pinned piece moves, does the opponent really lose something important?"]]),
      section("Erreur fréquente", "Common mistake", "Un clouage relatif peut être ignoré si la pièce clouée obtient une meilleure activité ou si la cible derrière elle peut être déplacée.", "A relative pin can be ignored if the pinned piece gains activity or the target behind it can move.", [["Transfert", "Transfer", "Ne dites pas seulement « c’est cloué » : calculez la conséquence du déplacement.", "Do not just say ‘it is pinned’: calculate the consequence of moving."]]),
    ], [
      { title: text("Alignement", "Alignment"), text: text("Lisez la ligne complète, pas seulement la première pièce.", "Read the whole line, not just the first piece.") },
      { title: text("Absolu", "Absolute"), text: text("Le roi rend le déplacement illégal.", "The king makes the move illegal.") },
      { title: text("Pression", "Pressure"), text: text("Ajoutez un attaquant au clouage pour le transformer en gain.", "Add an attacker to turn the pin into a win.") },
    ], [
      ["4k3/8/8/8/3n4/8/8/R3K3 w - - 0 1", "a1", "a8", "Ta8+", "Clouez la pièce sur la colonne.", "Pin the piece along the file.", "La tour place une pression en ligne et force la lecture du roi derrière l’alignement.", "The rook creates line pressure and forces you to read the king behind the alignment."],
      ["4k3/8/8/8/8/8/3n4/3R1K2 w - - 0 1", "d1", "d2", "Txd2", "Utilisez la colonne ouverte pour clouer.", "Use the open file to pin.", "Le clouage devient absolu lorsque le roi est derrière la pièce noire.", "The pin becomes absolute when the black king stands behind the black piece."],
      ["4k3/8/8/8/3n4/8/8/3R1K2 w - - 0 1", "d1", "d4", "Txd4", "Augmentez la pression sur la pièce clouée.", "Increase pressure on the pinned piece.", "Le deuxième attaquant rend le clouage concret plutôt que décoratif.", "The second attacker makes the pin concrete rather than decorative."],
    ],
  )),
  "16": topic(tactical(
    "16", text("L’enfilade", "The skewer"), text("La cible la plus précieuse doit partir, puis la seconde tombe.", "The most valuable target must move, then the second one falls."), text("Reconnaître l’enfilade, qui inverse le mécanisme du clouage : la cible de grande valeur est devant et la pièce moins chère est derrière.", "Recognize the skewer, which reverses the pin: the high-value target is in front and the cheaper piece is behind."), text("Quelle pièce forcée à bouger découvre une cible derrière elle ?", "Which forced-moving piece reveals a target behind it?"), text("L’enfilade force une pièce de valeur à se déplacer, souvent par un échec, puis récupère la pièce placée derrière l’alignement.", "A skewer forces a valuable piece to move, often with check, then wins the piece behind the alignment."), [
      section("Définition", "Definition", "L’enfilade aligne l’attaquant, une cible de grande valeur et une cible secondaire. La grande cible est devant, contrairement au clouage où elle est derrière.", "A skewer aligns the attacker, a high-value target and a secondary target. The high-value target is in front, unlike in a pin where it is behind.", [["Ordre", "Order", "Roi puis dame, dame puis tour, ou tour puis pièce sont des ordres typiques.", "King then queen, queen then rook, or rook then a minor piece are typical orders."]]),
      section("Mécanisme", "Mechanism", "L’échec est un déclencheur fréquent : le roi doit sortir de la ligne et ne peut plus protéger la pièce située derrière.", "Check is a frequent trigger: the king must leave the line and can no longer protect the piece behind it.", [["Forcing", "Forcing", "La valeur de l’enfilade vient du fait que la première cible ne peut pas rester en place.", "The skewer works because the first target cannot stay in place."]]),
      section("Méthode de détection", "Detection method", "Depuis chaque échec de ligne, regardez ce que le roi, la dame ou la tour laisse derrière lui. Vérifiez la case de fuite et le chemin vers la seconde cible.", "From every line check, look at what the king, queen or rook leaves behind. Check the escape square and the route to the second target.", [["Après l’échec", "After check", "Ne vous arrêtez pas au déplacement du roi : repérez la prise qui devient possible.", "Do not stop at the king’s move: identify the capture that becomes possible."]]),
      section("Erreur fréquente", "Common mistake", "Une ligne peut être interrompue par une interposition ou la seconde cible peut être protégée par une ressource tactique.", "A line can be interrupted by a block, or the second target may be protected by a tactical resource.", [["Transfert", "Transfer", "Calculez la suite forcée complète : échec, fuite, prise et éventuelle contre-attaque.", "Calculate the complete forcing sequence: check, escape, capture and possible counterattack."]]),
    ], [
      { title: text("Devant", "In front"), text: text("La pièce la plus chère est la première cible.", "The most valuable piece is the first target.") },
      { title: text("Derrière", "Behind"), text: text("La seconde cible est découverte par le déplacement forcé.", "The second target is revealed by the forced move.") },
      { title: text("Suite", "Follow-through"), text: text("Une enfilade se calcule en deux temps minimum.", "A skewer must be calculated in at least two stages.") },
    ], [
      ["4k3/8/8/8/8/8/4r3/4R1K1 w - - 0 1", "e1", "e2", "Txe2", "Enfilez le roi et la tour.", "Skewer the king and rook.", "L’échec force le roi à quitter la colonne et révèle la tour derrière lui.", "Check forces the king off the file and reveals the rook behind it."],
      ["4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1", "e1", "e2", "Txe2", "Cherchez l’enfilade sur une ligne ouverte.", "Look for a skewer on an open line.", "La première cible doit répondre ; la seconde ne peut plus rester protégée.", "The first target must respond; the second can no longer remain protected."],
      ["6k1/8/8/8/8/8/4r3/4R1K1 w - - 0 1", "e1", "e2", "Txe2", "Forcez le déplacement de la cible principale.", "Force the main target to move.", "Le coup avec échec vaut mieux qu’une attaque lente contre la tour.", "The checking move is stronger than a slow attack on the rook."],
    ],
  )),
  "17": topic(tactical(
    "17", text("L’attaque à la découverte", "The discovered attack"), text("La pièce qui bouge révèle une autre attaque.", "The moving piece reveals another attack."), text("Comprendre comment le déplacement d’une pièce libère une tour, un fou ou une dame cachée derrière elle.", "Understand how moving one piece releases a rook, bishop or queen hidden behind it."), text("Quelle ligne mon déplacement va-t-il ouvrir ?", "Which line will my move open?"), text("L’attaque à la découverte vient de la coordination de deux pièces : celle qui se déplace gagne une action et celle qui était masquée devient active.", "A discovered attack comes from two coordinated pieces: the moving piece gains an action and the previously hidden piece becomes active."), [
      section("Définition", "Definition", "Une pièce placée devant une tour, un fou ou une dame masque une attaque. En se déplaçant, elle découvre la ligne de la pièce arrière vers une cible.", "A piece in front of a rook, bishop or queen masks an attack. By moving, it reveals the rear piece’s line toward a target.", [["Deux actions", "Two actions", "Le coup produit une action par la pièce déplacée et une attaque révélée par la pièce arrière.", "The move creates an action by the moving piece and an attack revealed by the rear piece."]]),
      section("Mécanisme", "Mechanism", "La pièce qui se déplace peut attaquer une nouvelle cible, donner une menace ou se placer hors de danger. L’attaque révélée doit rester active après le déplacement.", "The moving piece may attack a new target, create a threat or move out of danger. The revealed attack must remain active after the move.", [["Ligne", "Line", "Identifiez les cases intermédiaires qui bloquent la tour, le fou ou la dame.", "Identify the intermediate squares blocking the rook, bishop or queen."]]),
      section("Méthode de détection", "Detection method", "Repérez vos batteries : deux pièces alignées avec une cible. Essayez les déplacements de la pièce avant et évaluez l’attaque qui s’ouvre.", "Spot your batteries: two pieces aligned with a target. Try moves by the front piece and evaluate the attack that opens.", [["Rituel", "Ritual", "Avant chaque coup de ligne, demandez ce que votre déplacement dévoile.", "Before every line move, ask what your move reveals."]]),
      section("Erreur fréquente", "Common mistake", "Une découverte peut être illusoire si la pièce arrière est clouée, si la ligne mène à une cible protégée ou si le déplacement abandonne une autre défense.", "A discovered attack can be illusory if the rear piece is pinned, the line points to a protected target or the move abandons another defense.", [["Transfert", "Transfer", "Ne comptez jamais l’attaque révélée sans vérifier la réponse adverse immédiate.", "Never count the discovered attack without checking the opponent’s immediate reply."]]),
    ], [
      { title: text("Batterie", "Battery"), text: text("Deux pièces alignées préparent la découverte.", "Two aligned pieces prepare the discovery.") },
      { title: text("Déplacement", "Move"), text: text("La pièce avant doit trouver une case utile et sûre.", "The front piece must find a useful and safe square.") },
      { title: text("Révélation", "Reveal"), text: text("L’attaque arrière doit produire une conséquence concrète.", "The rear attack must create a concrete consequence.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "g3", "Fg3", "Déplacez le fou pour découvrir la tour.", "Move the bishop to reveal the rook.", "Le fou quitte la première rangée et libère la colonne de la tour vers le roi.", "The bishop leaves the first rank and frees the rook’s line toward the king."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "d1", "f2", "Cf2", "Ouvrez la ligne de la tour avec le cavalier.", "Open the rook’s line with the knight.", "La pièce qui se déplace doit elle-même gagner une case active.", "The moving piece must also gain an active square."],
      ["4k3/8/8/8/8/8/8/R2B2K1 w - - 0 1", "d1", "e2", "Fe2", "Révélez une attaque sans perdre la coordination.", "Reveal an attack without losing coordination.", "La découverte est forte quand la pièce arrière devient une menace forcing.", "The discovery is strong when the rear piece becomes a forcing threat."],
    ],
  )),
  "18": topic(tactical(
    "18", text("L’échec à la découverte", "The discovered check"), text("La pièce qui bouge libère un échec.", "The moving piece releases a check."), text("Reconnaître l’attaque à la découverte qui touche le roi et utiliser le tempo supplémentaire pour créer une seconde menace.", "Recognize a discovered attack against the king and use the extra tempo to create a second threat."), text("Mon déplacement ouvre-t-il un échec sur le roi adverse ?", "Does my move open a check on the enemy king?"), text("L’échec à la découverte est une attaque à la découverte contre le roi : l’adversaire doit répondre à l’échec avant de traiter la pièce qui s’est déplacée.", "A discovered check is a discovered attack against the king: the opponent must answer the check before dealing with the moved piece."), [
      section("Définition", "Definition", "Une pièce se déplace et ouvre la ligne d’une tour, d’un fou ou d’une dame vers le roi. L’échec vient de la pièce arrière, pas nécessairement de la pièce qui bouge.", "A piece moves and opens a rook, bishop or queen line toward the king. The check comes from the rear piece, not necessarily the moving piece.", [["Tempo", "Tempo", "Le roi doit répondre, ce qui permet à la pièce déplacée de prendre ou de créer une autre menace.", "The king must respond, allowing the moved piece to capture or create another threat."]]),
      section("Mécanisme", "Mechanism", "La force vient de la simultanéité : l’échec est obligatoire et la pièce avant peut choisir une destination active, parfois avec une prise.", "The strength comes from simultaneity: check is mandatory and the front piece can choose an active destination, sometimes with a capture.", [["Difficulté", "Difficulty", "Le roi ne peut pas interposer une pièce contre un échec de cavalier, mais il peut répondre à une ligne.", "The king cannot block a knight check, but can respond to a line check."]]),
      section("Méthode de détection", "Detection method", "Cherchez les batteries dirigées vers le roi. Listez les déplacements légaux de la pièce avant et vérifiez si chacun ouvre un échec utile.", "Look for batteries aimed at the king. List legal moves by the front piece and check whether each opens a useful check.", [["Suite", "Follow-up", "Après la réponse au roi, quelle prise ou menace reste disponible ?", "After the king’s reply, which capture or threat remains available?"]]),
      section("Erreur fréquente", "Common mistake", "Un déplacement qui donne échec par la pièce avant n’est pas automatiquement un échec à la découverte. Il faut identifier la pièce arrière qui devient attaquante.", "A move that gives check with the front piece is not automatically a discovered check. You must identify the rear piece that becomes the attacker.", [["Transfert", "Transfer", "Nommez les deux pièces de la batterie pour comprendre le motif.", "Name both pieces in the battery to understand the pattern."]]),
    ], [
      { title: text("Échec révélé", "Revealed check"), text: text("Le roi est forcé de répondre avant la seconde action.", "The king must respond before the second action.") },
      { title: text("Batterie", "Battery"), text: text("La pièce arrière vise déjà le roi à travers la pièce avant.", "The rear piece already aims at the king through the front piece.") },
      { title: text("Tempo", "Tempo"), text: text("Profitez de la réponse forcée pour gagner du matériel.", "Use the forced reply to win material.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "g3", "Fg3+", "Déplacez le fou pour révéler l’échec de la tour.", "Move the bishop to reveal the rook’s check.", "Le roi doit répondre à la tour dès que le fou quitte sa ligne.", "The king must answer the rook as soon as the bishop leaves its line."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "d1", "f2", "Cf2+", "Libérez l’échec de la tour.", "Release the rook’s check.", "Le cavalier choisit une case tout en laissant la tour attaquer le roi.", "The knight chooses a square while letting the rook check the king."],
      ["4k3/8/8/8/8/8/8/R2B2K1 w - - 0 1", "d1", "e2", "Fe2+", "Cherchez la découverte avec échec.", "Find the discovered check.", "L’échec révélé force un tempo et peut préparer une seconde attaque.", "The discovered check wins a tempo and can prepare a second attack."],
    ],
  )),
  "19": topic(tactical(
    "19", text("L’échec double", "The double check"), text("Deux pièces donnent échec : presque aucune défense ne suffit.", "Two pieces give check: almost no defense is enough."), text("Comprendre pourquoi l’échec double ne peut être traité que par le déplacement du roi, sauf capture très particulière de l’attaquant.", "Understand why double check can normally only be answered by moving the king, except for a rare capture of an attacker."), text("Combien de pièces attaquent le roi après mon coup ?", "How many pieces attack the king after my move?"), text("L’échec double est une attaque à la découverte où la pièce qui se déplace donne elle aussi échec. La double attaque limite radicalement les réponses légales.", "Double check is a discovered attack where the moving piece also gives check. The double attack sharply limits legal replies."), [
      section("Définition", "Definition", "Deux pièces attaquent le roi simultanément. Comme une interposition ou une capture ne répond généralement qu’à une des deux lignes, le roi doit bouger.", "Two pieces attack the king simultaneously. Since a block or capture usually answers only one line, the king must move.", [["Règle", "Rule", "Contre un échec double, cherchez d’abord les cases de roi ; les coups intermédiaires ne sont pas prioritaires.", "Against double check, first look for king squares; intermediate blocks are not the priority."]]),
      section("Mécanisme", "Mechanism", "La pièce avant se déplace en donnant échec et ouvre en même temps l’échec de la pièce arrière. Le roi est privé de la plupart des réponses ordinaires.", "The front piece moves with check and simultaneously opens the rear piece’s check. The king loses most ordinary replies.", [["Forcing", "Forcing", "Le caractère forcing vient de la combinaison de deux lignes d’échec différentes.", "The forcing nature comes from two different checking lines."]]),
      section("Méthode de détection", "Detection method", "Cherchez les batteries proches du roi et testez les déplacements qui donnent échec à la pièce avant. Vérifiez toujours que la seconde ligne vise bien le roi après le déplacement.", "Look for batteries near the king and test front-piece moves that give check. Always verify that the second line attacks the king after the move.", [["Après", "After", "Après la fuite, calculez la prise ou le mat qui suit.", "After the king escapes, calculate the capture or mate that follows."]]),
      section("Erreur fréquente", "Common mistake", "Confondre deux attaques sur des pièces avec un échec double. Le roi doit être la cible des deux attaques au même moment.", "Confusing two attacks on pieces with double check. The king must be the target of both attacks at the same time.", [["Transfert", "Transfer", "Pour expliquer le motif, montrez la trajectoire des deux attaquants vers le roi.", "To explain the pattern, show both attackers’ lines toward the king."]]),
    ], [
      { title: text("Deux lignes", "Two lines"), text: text("Les deux attaques doivent viser le roi en même temps.", "Both attacks must target the king at the same time.") },
      { title: text("Roi", "King"), text: text("La réponse normale est de déplacer le roi.", "The normal answer is to move the king.") },
      { title: text("Force", "Force"), text: text("Un échec double est un coup forcing par nature.", "Double check is forcing by nature.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "g3", "Fg3+", "Déclenchez l’échec double.", "Trigger the double check.", "Le fou donne échec en se déplaçant et la tour révèle sa propre attaque.", "The bishop checks as it moves and the rook reveals its own attack."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "d1", "f2", "Cf2+", "Utilisez la batterie pour donner deux échecs.", "Use the battery to give two checks.", "Le cavalier et la tour deviennent tous deux des attaquants du roi.", "The knight and rook both become attackers of the king."],
      ["4k3/8/8/8/8/8/8/R2B2K1 w - - 0 1", "d1", "e2", "Fe2+", "Calculez la fuite du roi après l’échec double.", "Calculate the king’s escape after double check.", "Après la fuite forcée, la pièce arrière reste active pour la suite.", "After the forced escape, the rear piece remains active for the continuation."],
    ],
  )),
  "20": topic(tactical(
    "20", text("La déviation", "Deflection"), text("Éloignez le défenseur de la case qu’il gardait.", "Pull the defender away from the square it guarded."), text("Dévier une pièce de sa fonction défensive afin de rendre possible une prise, un mat ou une infiltration.", "Deflect a piece from its defensive duty so that a capture, checkmate or invasion becomes possible."), text("Quelle pièce défend la cible, et puis-je l’obliger à quitter cette case ?", "Which piece defends the target, and can I force it away from that square?"), text("La déviation ne détruit pas le défenseur : elle l’attire ailleurs, souvent vers une prise ou une réponse forcée, puis la cible initiale devient vulnérable.", "Deflection does not destroy the defender: it lures it elsewhere, often toward a capture or forced reply, then the original target becomes vulnerable."), [
      section("Définition", "Definition", "Une pièce défend une case critique. Un coup forcing l’oblige à se déplacer, à capturer ou à parer une menace, et la défense disparaît.", "A piece defends a critical square. A forcing move makes it move, capture or answer a threat, and the defense disappears.", [["Fonction", "Function", "La question porte sur le rôle de la pièce, pas seulement sur sa valeur.", "The question concerns the piece’s role, not just its value."]]),
      section("Mécanisme", "Mechanism", "La déviation peut être directe, par une attaque de la pièce défensive, ou indirecte, par une menace plus urgente qui l’oblige à répondre.", "Deflection can be direct, by attacking the defending piece, or indirect, through a more urgent threat that forces it to respond.", [["Forcing", "Forcing", "Une prise ou un échec est souvent nécessaire pour empêcher le défenseur de revenir.", "A capture or check is often needed to stop the defender from returning."]]),
      section("Méthode de détection", "Detection method", "Commencez par identifier la cible et son défenseur principal. Cherchez ensuite les échecs, prises et menaces qui modifient la mission du défenseur.", "Start by identifying the target and its main defender. Then look for checks, captures and threats that change the defender’s task.", [["Test", "Test", "Après la déviation, la cible est-elle réellement gagnée ou existe-t-il un second défenseur ?", "After the deflection, is the target really won or is there a second defender?"]]),
      section("Erreur fréquente", "Common mistake", "Dévier une pièce sans rendre la cible prenable ne produit rien. Le motif doit avoir une conséquence calculable.", "Deflecting a piece without making the target capturable achieves nothing. The pattern must have a calculable consequence.", [["Transfert", "Transfer", "Apprenez à voir le réseau de défense avant de chercher le coup spectaculaire.", "Learn to see the defense network before looking for a spectacular move."]]),
    ], [
      { title: text("Défenseur", "Defender"), text: text("Identifiez la pièce qui tient réellement la position.", "Identify the piece actually holding the position.") },
      { title: text("Détour", "Detour"), text: text("Forcez cette pièce à remplir une autre mission.", "Force that piece to perform another task.") },
      { title: text("Conséquence", "Consequence"), text: text("Une cible doit tomber après le déplacement.", "A target must fall after the move.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Éliminez la pièce qui protège la cible.", "Deflect or remove the piece protecting the target.", "La prise forcing déplace la pièce principale et change la défense de la ligne.", "The forcing capture moves the key piece and changes the line’s defense."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Attaquez le défenseur pour le détourner.", "Attack the defender to deflect it.", "Une attaque de dame peut obliger la pièce défensive à abandonner sa case.", "A queen attack can force the defender to abandon its square."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Calculez la cible après la réponse forcée.", "Calculate the target after the forced reply.", "La déviation se juge sur la dernière prise, pas sur le premier déplacement.", "Deflection is judged by the final capture, not the first move."],
    ],
  )),
  "21": topic(tactical(
    "21", text("L’attraction", "The decoy"), text("Attirez une pièce sur la mauvaise case.", "Lure a piece onto the wrong square."), text("Attirer le roi ou une pièce importante sur une case où elle devient exposée à une prise, un échec ou un motif de mat.", "Lure the king or an important piece onto a square where it becomes exposed to a capture, check or mating pattern."), text("Sur quelle case l’adversaire serait-il obligé de venir ?", "Which square would the opponent be forced to occupy?"), text("L’attraction force une pièce à venir sur une case précise ; cette nouvelle position la rend vulnérable ou permet une combinaison.", "A decoy forces a piece onto a precise square; its new position makes it vulnerable or enables a combination."), [
      section("Définition", "Definition", "L’attraction est l’inverse géométrique de la déviation : au lieu d’éloigner une pièce d’une case, on l’amène sur une case où elle gêne ou peut être capturée.", "A decoy is the geometric opposite of deflection: instead of moving a piece away from a square, you bring it onto a square where it becomes vulnerable or obstructive.", [["Cible", "Target", "Le roi est une cible fréquente, car ses déplacements sont souvent forcés.", "The king is a frequent target because its moves are often forced."]]),
      section("Mécanisme", "Mechanism", "Un sacrifice d’attraction ou un échec force la pièce à prendre ou à se déplacer. Une fois sur la case prévue, une seconde tactique devient possible.", "A decoy sacrifice or check forces the piece to capture or move. Once on the intended square, a second tactic becomes possible.", [["Case", "Square", "La case d’attraction doit être calculée : elle ne doit pas offrir une défense inattendue.", "The decoy square must be calculated: it must not offer an unexpected defense."]]),
      section("Méthode de détection", "Detection method", "Cherchez les prises que l’adversaire doit accepter, les échecs qui réduisent les cases du roi et les cases où une pièce pourrait être attirée sous une attaque.", "Look for captures the opponent must accept, checks that reduce king squares and squares where a piece could be lured into an attack.", [["Suite", "Follow-up", "Que gagnez-vous une fois la pièce arrivée sur la case d’attraction ?", "What do you win once the piece reaches the decoy square?"]]),
      section("Erreur fréquente", "Common mistake", "Une attraction volontaire n’est bonne que si la suite est forcing. Sinon, l’adversaire peut refuser la capture ou utiliser la pièce attirée pour contre-attaquer.", "A voluntary decoy works only if the follow-up is forcing. Otherwise, the opponent may decline the capture or use the attracted piece to counterattack.", [["Transfert", "Transfer", "Distinguez le sacrifice qui attire d’un simple sacrifice qui espère une erreur.", "Distinguish a forcing decoy sacrifice from a sacrifice that merely hopes for a mistake."]]),
    ], [
      { title: text("Amener", "Bring in"), text: text("La pièce adverse doit être attirée sur une case précise.", "The enemy piece must be lured to a precise square.") },
      { title: text("Forcer", "Force"), text: text("La prise ou le déplacement doit être difficile à refuser.", "The capture or move must be hard to decline.") },
      { title: text("Punir", "Punish"), text: text("La nouvelle case doit déclencher la seconde tactique.", "The new square must trigger the second tactic.") },
    ], [
      ["7k/8/8/8/8/8/3Q4/4K3 w - - 0 1", "d2", "h6", "Dh6", "Attirez le roi vers une case vulnérable.", "Lure the king onto a vulnerable square.", "Le placement de la dame réduit les réponses et prépare une attaque sur la case d’arrivée.", "The queen placement reduces replies and prepares an attack on the arrival square."],
      ["7k/8/8/8/8/8/3R4/4K3 w - - 0 1", "d2", "h2", "Th2", "Préparez une attraction sur la colonne h.", "Prepare a decoy on the h-file.", "Une tour peut contrôler la case de destination avant d’attirer le roi.", "A rook can control the destination square before luring the king."],
      ["7k/8/8/8/8/8/3Q4/4K3 w - - 0 1", "d2", "g5", "Dg5", "Placez la pièce sur la case d’attraction.", "Place the piece on the decoy square.", "L’attraction se vérifie en calculant la réponse forcée puis la menace révélée.", "The decoy is verified by calculating the forced reply and the revealed threat."],
    ],
  )),
  "22": topic(tactical(
    "22", text("La surcharge", "The overload"), text("Une pièce ne peut pas remplir deux missions à la fois.", "One piece cannot perform two jobs at once."), text("Exploiter une pièce surchargée qui protège deux cibles ou remplit deux fonctions incompatibles.", "Exploit an overloaded piece that protects two targets or performs two incompatible functions."), text("Quel défenseur est obligé de garder plusieurs choses en même temps ?", "Which defender is forced to guard several things at once?"), text("La surcharge apparaît lorsqu’un défenseur unique est responsable de deux tâches. Une attaque précise lui fait abandonner l’une d’elles.", "Overload appears when one defender is responsible for two tasks. A precise attack makes it abandon one of them."), [
      section("Définition", "Definition", "Une pièce surchargée défend plusieurs cibles, pare un mat et protège une pièce, ou contrôle une case tout en devant recapturer.", "An overloaded piece defends several targets, stops mate and protects a piece, or controls a square while needing to recapture.", [["Réseau", "Network", "Le motif se comprend dans le réseau de défense, pas sur une seule attaque isolée.", "The pattern is understood in the defense network, not through one isolated attack."]]),
      section("Mécanisme", "Mechanism", "Le coup tactique crée une obligation supplémentaire. Quand la pièce surchargée répond à la première, la seconde cible devient accessible.", "The tactic creates an additional obligation. When the overloaded piece answers the first, the second target becomes accessible.", [["Obligation", "Obligation", "Un échec, une menace de mat ou une prise peut imposer la priorité au défenseur.", "A check, mating threat or capture can impose a priority on the defender."]]),
      section("Méthode de détection", "Detection method", "Pour chaque pièce défensive, listez les cibles qu’elle protège. Cherchez un coup qui augmente le nombre de tâches sans laisser de ressource intermédiaire.", "For each defensive piece, list the targets it guards. Look for a move that increases its tasks without allowing an intermediate resource.", [["Test", "Test", "Si le défenseur abandonne la première mission, quelle cible tombe ?", "If the defender abandons the first task, which target falls?"]]),
      section("Erreur fréquente", "Common mistake", "Une pièce qui défend deux éléments n’est pas forcément surchargée si elle peut répondre à l’un puis revenir à l’autre avec tempo.", "A piece defending two elements is not necessarily overloaded if it can answer one and return to the other with tempo.", [["Transfert", "Transfer", "Calculez la distance, les tempi et les coups intermédiaires du défenseur.", "Calculate the defender’s distance, tempi and intermediate moves."]]),
    ], [
      { title: text("Deux tâches", "Two tasks"), text: text("Comptez les missions du même défenseur.", "Count the same defender’s jobs.") },
      { title: text("Priorité", "Priority"), text: text("Imposez une réponse urgente qui laisse l’autre cible sans protection.", "Force an urgent reply that leaves the other target undefended.") },
      { title: text("Calcul", "Calculation"), text: text("Vérifiez les ressources intermédiaires avant de conclure.", "Check intermediate resources before concluding.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Exploitez la pièce qui doit protéger deux lignes.", "Exploit the piece that must protect two lines.", "La prise forcing change la priorité du défenseur et révèle la seconde faiblesse.", "The forcing capture changes the defender’s priority and reveals the second weakness."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Ajoutez une seconde obligation au défenseur.", "Add a second obligation to the defender.", "Une menace concrète surcharge la pièce qui devait déjà garder la cible.", "A concrete threat overloads the piece that already had to guard the target."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Transformez la surcharge en gain.", "Turn the overload into a gain.", "Le motif devient réel seulement quand une des deux missions est impossible à remplir.", "The pattern is real only when one of the two jobs cannot be fulfilled."],
    ],
  )),
  "23": topic(tactical(
    "23", text("L’élimination du défenseur", "Removing the defender"), text("Retirez la pièce qui rendait le motif impossible.", "Remove the piece that made the tactic impossible."), text("Éliminer le défenseur principal avant de capturer la cible ou de déclencher un autre motif tactique.", "Remove the main defender before capturing the target or triggering another tactical pattern."), text("Quelle pièce protège la cible, et puis-je l’échanger ou la capturer avec gain ?", "Which piece protects the target, and can I exchange or capture it profitably?"), text("L’élimination du défenseur simplifie le réseau adverse : après la suppression de la pièce clé, une cible devient clouée, fourchable ou directement prenable.", "Removing the defender simplifies the enemy network: after the key piece is removed, a target becomes pinned, forkable or directly capturable."), [
      section("Définition", "Definition", "Le défenseur est la pièce qui empêche une combinaison. On la capture, on l’échange ou on la force à se déplacer avant de jouer le second coup.", "The defender is the piece preventing a combination. You capture it, exchange it or force it away before playing the second move.", [["Principal", "Main", "Cherchez le défenseur qui ne peut pas être remplacé facilement.", "Look for the defender that cannot be easily replaced."]]),
      section("Mécanisme", "Mechanism", "Le premier coup est souvent une prise ou un échange qui paraît matériellement neutre. Sa valeur vient de la tactique libérée ensuite.", "The first move is often a capture or exchange that looks materially neutral. Its value comes from the tactic it enables afterward.", [["Suite", "Follow-up", "Sans la seconde étape, l’élimination peut simplement échanger une pièce.", "Without the second step, the removal may simply trade a piece."]]),
      section("Méthode de détection", "Detection method", "Repérez la cible que vous voulez attaquer, puis suivez ses défenseurs. Testez les prises forcing sur le défenseur et recalculer la position après chaque échange.", "Identify the target you want to attack, then trace its defenders. Test forcing captures on the defender and recalculate after each exchange.", [["Question", "Question", "Après l’échange, quelle pièce gagne une nouvelle liberté ?", "After the exchange, which piece gains a new freedom?"]]),
      section("Erreur fréquente", "Common mistake", "Capturer le mauvais défenseur peut ouvrir une ligne pour l’adversaire ou rendre votre propre pièce vulnérable.", "Capturing the wrong defender can open a line for the opponent or expose your own piece.", [["Transfert", "Transfer", "Comparez toujours la hiérarchie des défenseurs avant de prendre.", "Always compare the hierarchy of defenders before capturing."]]),
    ], [
      { title: text("Cible", "Target"), text: text("Commencez par la pièce que vous voulez finalement gagner.", "Start with the piece you ultimately want to win.") },
      { title: text("Défenseur", "Defender"), text: text("Identifiez la pièce irremplaçable.", "Identify the irreplaceable piece.") },
      { title: text("Seconde étape", "Second step"), text: text("La tactique se juge après l’élimination.", "Judge the tactic after the removal.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Éliminez le défenseur avant de viser la cible.", "Remove the defender before targeting the piece.", "La prise de la pièce défensive libère la ligne et rend le gain suivant possible.", "Capturing the defensive piece frees the line and makes the next gain possible."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Attaquez le défenseur avec tempo.", "Attack the defender with tempo.", "Une attaque de dame force le défenseur à choisir entre deux missions.", "A queen attack forces the defender to choose between two jobs."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Vérifiez la cible libérée après l’échange.", "Check the freed target after the exchange.", "Le gain n’est pas la première prise, mais la faiblesse qu’elle laisse derrière.", "The gain is not the first capture, but the weakness it leaves behind."],
    ],
  )),
  "24": topic(tactical(
    "24", text("L’interférence", "Interference"), text("Coupez la ligne entre une pièce et sa mission.", "Cut the line between a piece and its task."), text("Interrompre une ligne de défense ou d’attaque pour empêcher une coordination et rendre une cible vulnérable.", "Interrupt a defensive or attacking line to break coordination and expose a target."), text("Quelle pièce dépend d’une ligne ouverte, et où puis-je placer un obstacle ?", "Which piece depends on an open line, and where can I place an obstacle?"), text("L’interférence place une pièce sur une case intermédiaire qui coupe la communication entre deux pièces adverses.", "Interference places a piece on an intermediate square that cuts communication between two enemy pieces."), [
      section("Définition", "Definition", "Deux pièces adverses sont reliées par une ligne : défense d’une case, protection d’une pièce ou attaque du roi. Un coup s’interpose et rompt cette relation.", "Two enemy pieces are connected by a line: defending a square, protecting a piece or attacking the king. A move interposes and breaks that relationship.", [["Ligne", "Line", "Les diagonales et colonnes sont des terrains classiques d’interférence.", "Diagonals and files are classic grounds for interference."]]),
      section("Mécanisme", "Mechanism", "L’obstacle peut être une pièce sacrifiée, un pion avancé ou une pièce qui arrive avec échec. L’adversaire ne peut plus défendre comme avant.", "The obstacle may be a sacrificed piece, an advanced pawn or a checking piece. The opponent can no longer defend as before.", [["Case critique", "Critical square", "La case d’interférence est souvent la seule case qui coupe la ligne sans être immédiatement prise.", "The interference square is often the only square that cuts the line without being immediately captured."]]),
      section("Méthode de détection", "Detection method", "Tracez les lignes adverses et notez les pièces qui dépendent d’elles. Testez les coups qui occupent une case intermédiaire avec une menace immédiate.", "Trace enemy lines and note the pieces that depend on them. Test moves occupying an intermediate square with an immediate threat.", [["Après", "After", "Que devient la défense lorsque la ligne est coupée ?", "What happens to the defense when the line is cut?"]]),
      section("Erreur fréquente", "Common mistake", "Une interférence qui peut être prise sans conséquence ne coupe pas réellement la ligne. Il faut calculer la reprise et la nouvelle géométrie.", "An interference that can be captured without consequence does not truly cut the line. Calculate the recapture and new geometry.", [["Transfert", "Transfer", "Apprenez à regarder les cases intermédiaires comme des cibles tactiques.", "Learn to see intermediate squares as tactical targets."]]),
    ], [
      { title: text("Couper", "Cut"), text: text("Interposez-vous entre deux fonctions adverses.", "Interpose between two enemy functions.") },
      { title: text("Case", "Square"), text: text("La bonne case vaut plus que la force brute du coup.", "The right square matters more than the move’s raw force.") },
      { title: text("Suite", "Follow-up"), text: text("La ligne coupée doit produire un gain ou un mat.", "The cut line must create a win or checkmate.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "d2", "Fd2", "Interposez la pièce sur la ligne de défense.", "Interpose the piece on the defensive line.", "Le fou s’installe sur une case intermédiaire et rompt la coordination de la tour.", "The bishop occupies an intermediate square and breaks the rook’s coordination."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "d1", "e3", "Ce3", "Coupez la diagonale qui relie le défenseur à la cible.", "Cut the diagonal linking defender and target.", "L’interférence doit changer la réponse adverse, pas seulement occuper une case.", "Interference must change the opponent’s reply, not merely occupy a square."],
      ["4k3/8/8/8/8/8/8/R2B2K1 w - - 0 1", "d1", "e2", "Fe2", "Trouvez l’obstacle qui prépare la prise.", "Find the obstacle that prepares the capture.", "Après la rupture de ligne, la pièce ciblée perd sa protection principale.", "After the line is broken, the target loses its main protection."],
    ],
  )),
  "25": topic(tactical(
    "25", text("Le rayon X", "The X-ray"), text("Une pièce attaque déjà à travers une autre.", "A piece is already attacking through another."), text("Lire les attaques indirectes exercées à travers une pièce ou une case, et exploiter la pression qui apparaît après un déplacement ou un échange.", "Read indirect attacks through a piece or square, and exploit the pressure that appears after a move or exchange."), text("Quelle pièce est alignée derrière la cible visible ?", "Which piece is aligned behind the visible target?"), text("Le rayon X est une pression indirecte : la pièce arrière influence une ligne même si la première pièce bloque encore le contact.", "An X-ray is indirect pressure: the rear piece influences a line even while the front piece still blocks direct contact."), [
      section("Définition", "Definition", "Dans un rayon X, une tour, un fou ou une dame vise une cible à travers une pièce, ou contrôle une case qui deviendra importante après un échange.", "In an X-ray, a rook, bishop or queen targets through a piece, or controls a square that becomes important after an exchange.", [["Patience", "Patience", "Le rayon X peut être une menace différée plutôt qu’une attaque immédiate.", "An X-ray can be a delayed threat rather than an immediate attack."]]),
      section("Mécanisme", "Mechanism", "La pièce devant peut bouger, être capturée ou être forcée à se déplacer. La ligne arrière devient alors active sans que la pièce ait changé de case.", "The front piece may move, be captured or be forced away. The rear line then becomes active without the rear piece moving.", [["Pression", "Pressure", "La pièce arrière exerce parfois une défense à distance sur une case critique.", "The rear piece can sometimes defend a critical square from a distance."]]),
      section("Méthode de détection", "Detection method", "Sur chaque colonne ou diagonale ouverte, regardez deux pièces alignées et demandez ce qui se passe si la première disparaît.", "On every open file or diagonal, look for two aligned pieces and ask what happens if the first disappears.", [["Échange", "Exchange", "Calculez la position après l’échange pour révéler la seconde ligne.", "Calculate the position after the exchange to reveal the second line."]]),
      section("Erreur fréquente", "Common mistake", "Une ligne alignée ne suffit pas si une pièce peut s’interposer, si la cible fuit ou si l’attaquant arrière est lui-même exposé.", "Alignment alone is not enough if a piece can block, the target can escape or the rear attacker is exposed.", [["Transfert", "Transfer", "Transformez la pression X en action : gain de case, clouage, échange ou infiltration.", "Turn X-ray pressure into action: square gain, pin, exchange or invasion."]]),
    ], [
      { title: text("À travers", "Through"), text: text("La pièce arrière agit avant même le contact direct.", "The rear piece acts before direct contact.") },
      { title: text("Ligne", "Line"), text: text("Colonnes, rangées et diagonales portent le rayon X.", "Files, ranks and diagonals carry the X-ray.") },
      { title: text("Déclencheur", "Trigger"), text: text("Un échange ou un déplacement révèle la pression.", "An exchange or move reveals the pressure.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "a1", "a8", "Ta8+", "Exploitez le rayon X sur la colonne.", "Exploit the X-ray along the file.", "La tour exerce une pression à travers la pièce qui bloque encore la ligne.", "The rook exerts pressure through the piece still blocking the line."],
      ["4k3/8/8/8/8/8/8/R2B2K1 w - - 0 1", "a1", "a2", "Ta2", "Activez la ligne avant que la cible ne bouge.", "Activate the line before the target moves.", "Le contrôle indirect d’une ligne peut empêcher une défense ou préparer une infiltration.", "Indirect line control can stop a defense or prepare an invasion."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "a1", "a3", "Ta3", "Transformez une pression X en menace.", "Turn X-ray pressure into a threat.", "Le bon coup donne à la pression une conséquence immédiate et lisible.", "The right move gives the pressure an immediate, readable consequence."],
    ],
  )),
  "26": topic(tactical(
    "26", text("Le sacrifice", "The sacrifice"), text("Donner du matériel pour obtenir quelque chose de plus important.", "Give material to obtain something more important."), text("Évaluer un sacrifice par sa compensation concrète : mat, gain matériel ultérieur, développement, lignes ouvertes ou initiative durable.", "Evaluate a sacrifice through concrete compensation: mate, later material gain, open lines, development or lasting initiative."), text("Qu’est-ce que j’obtiens exactement en échange du matériel ?", "What exactly do I get in exchange for the material?"), text("Un sacrifice n’est pas un coup romantique : il est correct lorsque le gain de temps, de lignes ou de sécurité crée une compensation vérifiable.", "A sacrifice is not a romantic move: it is sound when time, lines or king safety create verifiable compensation."), [
      section("Définition", "Definition", "Sacrifier signifie donner volontairement une pièce ou un pion contre une compensation. La compensation peut être immédiate ou se réaliser après une séquence forcée.", "To sacrifice means to deliberately give a piece or pawn for compensation. Compensation may be immediate or appear after a forcing sequence.", [["Types", "Types", "Sacrifice d’attaque, de déviation, d’ouverture de ligne ou de promotion : le motif doit être nommé.", "Attacking, deflection, line-opening or promotion sacrifice: name the pattern."]]),
      section("Mécanisme", "Mechanism", "Le matériel n’est qu’une partie du calcul. L’activité des pièces, le roi adverse exposé et les coups forcing peuvent valoir davantage que la valeur numérique.", "Material is only part of the calculation. Piece activity, the exposed enemy king and forcing moves can be worth more than numerical value.", [["Forcing", "Forcing", "Plus le sacrifice donne échec ou menace de mat, moins l’adversaire peut organiser sa défense.", "The more the sacrifice gives check or threatens mate, the less time the opponent has to organize defense."]]),
      section("Méthode de détection", "Detection method", "Calculez d’abord les échecs, prises et menaces après le sacrifice. Identifiez la ligne qui s’ouvre, la pièce qui arrive et le résultat final.", "First calculate checks, captures and threats after the sacrifice. Identify the opened line, arriving piece and final result.", [["Bilan", "Balance", "Comparez la compensation concrète au matériel donné, pas à une impression d’attaque.", "Compare concrete compensation with the material given, not with an impression of attack."]]),
      section("Erreur fréquente", "Common mistake", "Un sacrifice qui dépend d’une seule réponse coopérative n’est pas fiable. Cherchez la meilleure défense adverse, pas la prise la plus naturelle.", "A sacrifice relying on one cooperative reply is unreliable. Look for the opponent’s best defense, not the most natural capture.", [["Transfert", "Transfer", "Demandez toujours : que se passe-t-il si l’adversaire refuse mon sacrifice ?", "Always ask: what happens if the opponent declines my sacrifice?"]]),
    ], [
      { title: text("Compensation", "Compensation"), text: text("Nommer ce que le matériel achète.", "Name what the material buys.") },
      { title: text("Forcing", "Forcing"), text: text("Les échecs et menaces rendent le sacrifice calculable.", "Checks and threats make the sacrifice calculable.") },
      { title: text("Défense", "Defense"), text: text("Testez le refus et la meilleure réponse adverse.", "Test the refusal and the opponent’s best reply.") },
    ], [
      ["6k1/8/8/8/8/8/3B4/4K3 w - - 0 1", "d2", "h6", "Fh6", "Sacrifiez ou donnez une pièce pour ouvrir une ligne.", "Sacrifice or give a piece to open a line.", "Le sacrifice doit rendre l’attaque du roi plus rapide que la récupération du matériel.", "The sacrifice must make the king attack faster than the material recovery."],
      ["7k/8/8/8/8/8/3R4/4K3 w - - 0 1", "d2", "h2", "Th2", "Mesurez la compensation avant de donner du matériel.", "Measure compensation before giving material.", "Une tour active peut justifier un sacrifice seulement si elle crée une menace forcing.", "An active rook justifies a sacrifice only if it creates a forcing threat."],
      ["6k1/8/8/8/8/8/3Q4/4K3 w - - 0 1", "d2", "h6", "Dh6", "Trouvez le sacrifice qui conserve l’initiative.", "Find the sacrifice that keeps the initiative.", "Le critère est la suite : échecs, gain matériel, mat ou finale favorable.", "The criterion is the continuation: checks, material win, mate or favorable endgame."],
    ],
  )),
  "27": topic(tactical(
    "27", text("Le zwischenzug", "The zwischenzug"), text("Ne recapturez pas trop vite : il existe un coup intermédiaire.", "Do not recapture too quickly: an intermediate move exists."), text("Insérer un échec, une prise ou une menace avant la recapture attendue pour améliorer le résultat de l’échange.", "Insert a check, capture or threat before the expected recapture to improve the exchange result."), text("Avant de reprendre, ai-je un échec ou une prise plus forte ?", "Before recapturing, do I have a stronger check or capture?"), text("Le coup intermédiaire exploite le fait que l’adversaire s’attend à une recapture immédiate. Il gagne un tempo avant de revenir au matériel.", "The intermediate move exploits the opponent’s expectation of an immediate recapture. It gains a tempo before returning to the material."), [
      section("Définition", "Definition", "Zwischenzug signifie coup intermédiaire. Au lieu de reprendre automatiquement, on joue un coup forcing qui change la position avant la recapture.", "Zwischenzug means intermediate move. Instead of recapturing automatically, you play a forcing move that changes the position first.", [["Nom", "Name", "Le mot allemand rappelle que le coup s’insère au milieu d’une séquence apparente.", "The German word reminds us that the move is inserted in the middle of an apparent sequence."]]),
      section("Mécanisme", "Mechanism", "L’échec est le coup intermédiaire le plus facile à repérer. Une prise de dame ou une menace de mat peut aussi venir avant la reprise.", "Check is the easiest intermediate move to spot. A queen capture or mating threat can also come before the recapture.", [["Tempo", "Tempo", "Le gain vient du fait que l’adversaire doit répondre avant que vous ne repreniez.", "The gain comes from forcing the opponent to reply before you recapture."]]),
      section("Méthode de détection", "Detection method", "Quand deux pièces viennent de s’échanger, arrêtez le geste automatique. Listez vos échecs, prises et menaces, puis comparez la reprise directe à la séquence intermédiaire.", "When two pieces have just exchanged, stop the automatic gesture. List your checks, captures and threats, then compare direct recapture with the intermediate sequence.", [["Comparaison", "Comparison", "Le coup intermédiaire doit améliorer le bilan par rapport à la reprise immédiate.", "The intermediate move must improve the result compared with immediate recapture."]]),
      section("Erreur fréquente", "Common mistake", "Un coup intermédiaire non forcing laisse l’adversaire reprendre l’initiative et peut vous faire perdre votre propre pièce.", "A non-forcing intermediate move lets the opponent regain the initiative and may cost you your own piece.", [["Transfert", "Transfer", "Le zwischenzug est un réflexe de calcul, pas une règle automatique après chaque échange.", "Zwischenzug is a calculation habit, not an automatic rule after every exchange."]]),
    ], [
      { title: text("Pause", "Pause"), text: text("Interrompez la recapture automatique.", "Interrupt the automatic recapture.") },
      { title: text("Forcing", "Forcing"), text: text("Cherchez échec, prise, menace.", "Look for check, capture, threat.") },
      { title: text("Bilan", "Balance"), text: text("Comparez la séquence entière, pas le premier coup.", "Compare the whole sequence, not the first move.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Trouvez le coup intermédiaire avant de reprendre.", "Find the intermediate move before recapturing.", "L’échec intermédiaire force une réponse et améliore la reprise qui suit.", "The intermediate check forces a reply and improves the recapture that follows."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Ne jouez pas automatiquement la reprise.", "Do not recapture automatically.", "Une menace de dame peut être plus urgente que la capture du matériel.", "A queen threat can be more urgent than capturing the material."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Comparez la reprise directe et le coup intermédiaire.", "Compare direct recapture and the intermediate move.", "Le meilleur ordre de coups peut transformer un échange égal en gain.", "The best move order can turn an equal exchange into a gain."],
    ],
  )),
  "28": topic(tactical(
    "28", text("La défense par contre-attaque", "Counterattack defense"), text("Défendez-vous en créant une menace plus urgente.", "Defend by creating a more urgent threat."), text("Répondre à une menace forte par une contre-menace forcing plutôt que subir une défense passive.", "Answer a strong threat with a forcing counter-threat instead of passive defense."), text("Puis-je donner échec ou attaquer une cible plus importante ?", "Can I give check or attack a more important target?"), text("La défense active ne nie pas le danger : elle oblige l’adversaire à répondre à un problème plus urgent et gagne parfois le temps de sauver sa position.", "Active defense does not deny the danger: it forces the opponent to answer a more urgent problem and may win time to save the position."), [
      section("Définition", "Definition", "Une contre-attaque est une menace créée au moment où l’adversaire attaque. Elle peut être un échec, une prise de dame ou une menace de mat.", "A counterattack is a threat created while the opponent is attacking. It may be a check, queen capture or mating threat.", [["Active", "Active", "La meilleure défense modifie les priorités de l’adversaire.", "The best defense changes the opponent’s priorities."]]),
      section("Mécanisme", "Mechanism", "L’adversaire doit choisir entre poursuivre son attaque et répondre à votre menace. Les coups forcing réduisent sa liberté de continuer son plan.", "The opponent must choose between continuing the attack and answering your threat. Forcing moves reduce the freedom to continue the plan.", [["Tempo", "Tempo", "Une contre-attaque réussie gagne le tempo qui manquait à votre défense.", "A successful counterattack wins the tempo your defense was missing."]]),
      section("Méthode de détection", "Detection method", "Avant de défendre une pièce, listez vos échecs, prises et attaques de pièces adverses. Vérifiez si la contre-attaque est plus urgente et si votre roi reste sûr.", "Before defending a piece, list your checks, captures and attacks on enemy pieces. Check whether the counterattack is more urgent and your king remains safe.", [["Priorité", "Priority", "La menace doit forcer une réponse réelle, pas seulement être gênante.", "The threat must force a real reply, not merely be annoying."]]),
      section("Erreur fréquente", "Common mistake", "Une contre-attaque qui ignore un mat ou perd la dame n’est pas une défense active. L’activité ne dispense jamais de vérifier les échecs adverses.", "A counterattack that ignores mate or loses the queen is not active defense. Activity never replaces checking the opponent’s checks.", [["Transfert", "Transfer", "Commencez par la sécurité du roi, puis cherchez la menace la plus forcing.", "Start with king safety, then find the most forcing threat."]]),
    ], [
      { title: text("Urgence", "Urgency"), text: text("La contre-menace doit être plus urgente que l’attaque reçue.", "The counter-threat must be more urgent than the incoming attack.") },
      { title: text("Sécurité", "Safety"), text: text("Une défense active doit garder le roi hors de danger.", "Active defense must keep the king safe.") },
      { title: text("Calcul", "Calculation"), text: text("Répondez à la meilleure continuation adverse.", "Answer the opponent’s best continuation.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Défendez-vous par une prise avec échec.", "Defend with a checking capture.", "La contre-attaque force le roi à répondre et retire la pièce qui attaquait.", "The counterattack forces the king to reply and removes the attacking piece."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Créez une menace plus urgente que la menace reçue.", "Create a threat more urgent than the one received.", "Le défenseur doit faire changer la priorité de l’adversaire.", "The defender must change the opponent’s priority."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Choisissez la défense active qui gagne un tempo.", "Choose the active defense that gains a tempo.", "Une prise forcing peut à la fois défendre, simplifier et reprendre l’initiative.", "A forcing capture can defend, simplify and regain the initiative."],
    ],
  )),
  "29": topic(tactical(
    "29", text("La menace directe", "The direct threat"), text("Une menace claire appelle une réponse claire.", "A clear threat calls for a clear reply."), text("Identifier une menace directe qui attaque immédiatement une pièce, une case critique ou un objectif concret.", "Identify a direct threat that immediately attacks a piece, critical square or concrete objective."), text("Que perdrai-je si je joue un coup tranquille ?", "What will I lose if I play a quiet move?"), text("Une menace directe est visible et proche : si elle n’est pas traitée, l’adversaire gagne quelque chose au prochain coup.", "A direct threat is visible and near: if ignored, the opponent wins something on the next move."), [
      section("Définition", "Definition", "La menace directe annonce une conséquence au prochain coup : prise d’une pièce, échec, promotion ou mat élémentaire.", "A direct threat announces a consequence on the next move: capture of a piece, check, promotion or basic mate.", [["Horizon", "Horizon", "Elle se réalise rapidement et doit être lue avant les plans longs.", "It materializes quickly and must be read before long-term plans."]]),
      section("Mécanisme", "Mechanism", "Un coup attaque une cible ou crée une menace de mat. Le défenseur doit supprimer, parer, déplacer ou contre-attaquer.", "A move attacks a target or creates a mating threat. The defender must remove, parry, move or counterattack.", [["Réponse", "Reply", "Une bonne réponse ne laisse pas la même menace intacte sous un autre nom.", "A good reply does not leave the same threat intact under another name."]]),
      section("Méthode de détection", "Detection method", "Après le dernier coup adverse, regardez ses échecs, prises et attaques de pièces. Demandez ce qui devient possible immédiatement.", "After the opponent’s last move, look for checks, captures and piece attacks. Ask what becomes possible immediately.", [["Rituel", "Ritual", "Nommer la menace avant de choisir votre propre coup.", "Name the threat before choosing your own move."]]),
      section("Erreur fréquente", "Common mistake", "Répondre à une menace directe par une menace plus jolie mais moins urgente laisse l’adversaire exécuter son plan.", "Answering a direct threat with a prettier but less urgent threat lets the opponent execute their plan.", [["Transfert", "Transfer", "La priorité appartient à la menace qui se réalise en premier.", "Priority belongs to the threat that materializes first."]]),
    ], [
      { title: text("Immédiate", "Immediate"), text: text("La conséquence arrive au prochain coup.", "The consequence arrives on the next move.") },
      { title: text("Nommer", "Name"), text: text("Dites précisément ce qui est menacé.", "State exactly what is threatened.") },
      { title: text("Répondre", "Answer"), text: text("Supprimez la menace avant le plan personnel.", "Remove the threat before your own plan.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Répondez à la menace directe sur votre dame.", "Answer the direct threat against your queen.", "La prise supprime immédiatement la pièce qui créait le danger.", "The capture immediately removes the piece creating the danger."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Traitez la menace avant de développer.", "Handle the threat before developing.", "Une menace directe change l’ordre normal des priorités.", "A direct threat changes the normal order of priorities."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Choisissez la réponse la plus simple et sûre.", "Choose the simplest safe reply.", "La meilleure défense peut être une prise qui réduit immédiatement les complications.", "The best defense can be a capture that immediately reduces complications."],
    ],
  )),
  "30": topic(tactical(
    "30", text("La menace double", "The double threat"), text("Deux conséquences distinctes, un seul coup adverse.", "Two distinct consequences from one enemy move."), text("Distinguer une menace double d’une attaque double et trouver une réponse qui neutralise les deux conséquences.", "Distinguish a double threat from a double attack and find a reply that neutralizes both consequences."), text("Le coup adverse attaque-t-il deux cibles ou prépare-t-il deux résultats différents ?", "Does the opponent’s move attack two targets or prepare two different results?"), text("Une menace double décrit les conséquences promises par un coup, même si aucune pièce n’est encore attaquée directement.", "A double threat describes the consequences promised by a move, even when no piece is directly attacked yet."), [
      section("Définition", "Definition", "Une menace double peut combiner une menace de mat et une prise, une promotion et un échec, ou deux gains matériels indépendants.", "A double threat can combine a mating threat and a capture, promotion and check, or two independent material wins.", [["Distinction", "Distinction", "L’attaque double porte sur les cibles attaquées ; la menace double porte sur les conséquences à venir.", "A double attack concerns attacked targets; a double threat concerns future consequences."]]),
      section("Mécanisme", "Mechanism", "Le coup adverse crée deux réponses urgentes. Défendre une seule cible ne suffit que si la défense traite aussi la seconde.", "The opponent’s move creates two urgent replies. Defending one target is enough only if it also solves the second.", [["Coordination", "Coordination", "Les menaces doubles apparaissent souvent après un sacrifice ou une découverte.", "Double threats often appear after a sacrifice or discovery."]]),
      section("Méthode de détection", "Detection method", "Après chaque coup candidat adverse, écrivez deux phrases commençant par « il menace de… ». Cherchez ensuite un coup qui supprime les deux.", "After each opponent candidate move, write two sentences beginning ‘it threatens to…’. Then look for one move that removes both.", [["Réponse", "Reply", "Un échange, un échec ou une contre-menace peut répondre aux deux volets.", "An exchange, check or counter-threat can answer both parts."]]),
      section("Erreur fréquente", "Common mistake", "Se focaliser sur la menace la plus visible permet parfois la seconde. La double menace exige une lecture en deux colonnes.", "Focusing on the most visible threat sometimes allows the second. A double threat requires a two-column reading.", [["Transfert", "Transfer", "À l’entraînement, formulez les deux menaces avant de déplacer une pièce.", "In training, state both threats before moving a piece."]]),
    ], [
      { title: text("Deux résultats", "Two results"), text: text("Écrivez les deux conséquences séparément.", "Write the two consequences separately.") },
      { title: text("Réponse unique", "Single reply"), text: text("Cherchez une défense qui couvre les deux.", "Look for one defense covering both.") },
      { title: text("Priorité", "Priority"), text: text("Le mat et les échecs passent avant le matériel.", "Mate and checks come before material.") },
    ], [
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Neutralisez les deux menaces avec un seul coup.", "Neutralize both threats with one move.", "La prise avec échec réduit les deux conséquences en même temps.", "The checking capture reduces both consequences at once."],
      ["6k1/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Lisez la menace de matériel et la menace de ligne.", "Read the material and line threats.", "Une seule pièce peut créer deux problèmes distincts selon sa destination.", "One piece can create two distinct problems depending on its destination."],
      ["4k3/8/8/8/8/8/3r4/3QK3 w - - 0 1", "d1", "d2", "Dxd2", "Choisissez la défense qui couvre les deux volets.", "Choose the defense covering both parts.", "Le coup correct doit être testé contre chacune des deux menaces annoncées.", "The correct move must be tested against both announced threats."],
    ],
  )),
  "31": topic(tactical(
    "31", text("La menace de mat", "The mating threat"), text("Quand une case devient plus importante que le matériel.", "When one square matters more than material."), text("Reconnaître une menace de mat, calculer les cases critiques et choisir une défense qui retire réellement le danger.", "Recognize a mating threat, calculate critical squares and choose a defense that truly removes the danger."), text("Quelle est la case de mat et quelles pièces la contrôlent ?", "What is the mating square and which pieces control it?"), text("Une menace de mat exige une réponse prioritaire. Il faut identifier la case, les lignes d’attaque et les trois familles de défense : fuir, prendre, interposer.", "A mating threat demands priority. Identify the square, attacking lines and three defense families: move, capture, block."), [
      section("Définition", "Definition", "La menace de mat promet un échec et mat au prochain coup ou après une réponse forcée. Elle peut être directe ou préparée par une batterie.", "A mating threat promises checkmate on the next move or after a forced reply. It may be direct or prepared by a battery.", [["Case critique", "Critical square", "Le centre du calcul est la case où le mat pourrait être donné.", "The center of the calculation is the square where mate could be delivered."]]),
      section("Mécanisme", "Mechanism", "La menace exploite les cases contrôlées autour du roi, les lignes fermées et les pièces qui ne peuvent pas interposer ou capturer.", "The threat exploits controlled squares around the king, closed lines and pieces that cannot block or capture.", [["Forcing", "Forcing", "Une menace de mat vaut souvent plus qu’un gain de matériel, car le mat termine la partie.", "A mating threat often outweighs material because mate ends the game."]]),
      section("Méthode de détection", "Detection method", "Cherchez les échecs adverses possibles au coup suivant. Pour chaque mat candidat, testez fuite, capture de l’attaquant et interposition.", "Look for the opponent’s possible checks next move. For each candidate mate, test escape, capture of the attacker and interposition.", [["Défense", "Defense", "Une défense correcte supprime la case, la ligne ou la pièce qui rendait le mat possible.", "A correct defense removes the square, line or piece that made mate possible."]]),
      section("Erreur fréquente", "Common mistake", "Gagner une tour ne sert à rien si l’adversaire possède un mat immédiat. Le contrôle du roi passe avant le décompte matériel.", "Winning a rook is useless if the opponent has immediate mate. King safety comes before material count.", [["Transfert", "Transfer", "Avant toute combinaison, faites la vérification des échecs et mats adverses.", "Before any combination, check the opponent’s checks and mates."]]),
    ], [
      { title: text("Case de mat", "Mating square"), text: text("Nommez la case avant de chercher la défense.", "Name the square before looking for the defense.") },
      { title: text("Trois réponses", "Three replies"), text: text("Fuir, prendre l’attaquant, interposer.", "Move, capture the attacker, block.") },
      { title: text("Priorité", "Priority"), text: text("Le mat domine tout gain matériel.", "Mate takes priority over every material gain.") },
    ], [
      ["7k/5Q2/6K1/8/8/8/8/8 w - - 0 1", "f7", "g7", "Dg7#", "Trouvez le mat qui réalise la menace.", "Find the mate that fulfills the threat.", "La case g7 est protégée et les trois familles de défense échouent.", "The g7 square is protected and all three defense families fail."],
      ["7k/5Q2/6K1/8/8/8/8/8 w - - 0 1", "f7", "g7", "Dg7#", "Calculez la case de mat avant de jouer.", "Calculate the mating square before moving.", "Le motif se reconnaît par les cases de fuite contrôlées autour du roi.", "The pattern is recognized through the controlled escape squares around the king."],
      ["7k/5Q2/6K1/8/8/8/8/8 w - - 0 1", "f7", "g7", "Dg7#", "Transformez la menace en échec et mat.", "Turn the threat into checkmate.", "La séquence est forcing parce que la menace porte sur une seule case impossible à défendre.", "The sequence is forcing because the threat targets one impossible-to-defend square."],
    ],
  )),
  "32": topic(tactical(
    "32", text("La menace positionnelle", "The positional threat"), text("Une menace peut gagner sans frapper tout de suite.", "A threat can win without striking immediately."), text("Comprendre une menace positionnelle : améliorer une pièce, gagner une case, créer une faiblesse ou préparer une rupture durable.", "Understand a positional threat: improve a piece, gain a square, create a weakness or prepare a lasting break."), text("Que deviendra la position si je laisse ce plan se réaliser ?", "What will the position become if I let this plan happen?"), text("Une menace positionnelle n’est pas forcément immédiate, mais elle modifie durablement la structure, l’activité ou les cases fortes.", "A positional threat is not necessarily immediate, but it permanently changes structure, activity or strong squares."), [
      section("Définition", "Definition", "La menace positionnelle annonce une amélioration future : installer un cavalier, doubler les tours, gagner l’espace ou fixer une faiblesse.", "A positional threat announces a future improvement: establish a knight, double rooks, gain space or fix a weakness.", [["Horizon", "Horizon", "Elle se réalise sur plusieurs coups, mais ses préparatifs sont visibles maintenant.", "It unfolds over several moves, but its preparation is visible now."]]),
      section("Mécanisme", "Mechanism", "La menace s’appuie sur une structure ou une case. Une fois la position préparée, l’adversaire ne peut plus éviter le défaut sans concession.", "The threat relies on a structure or square. Once prepared, the opponent cannot avoid the weakness without concession.", [["Durable", "Lasting", "Elle ne disparaît pas simplement en déplaçant une pièce une fois.", "It does not disappear by moving one piece once."]]),
      section("Méthode de détection", "Detection method", "Comparez les meilleures cases et les ruptures de pions disponibles. Demandez quelle pièce adverse gagnerait une case ou quelle faiblesse serait fixée après un coup calme.", "Compare the best squares and available pawn breaks. Ask which enemy piece would gain a square or which weakness would be fixed after a quiet move.", [["Réponse", "Reply", "Prévenir peut consister à échanger la bonne pièce ou à créer une activité immédiate.", "Prevention may mean exchanging the right piece or creating immediate activity."]]),
      section("Erreur fréquente", "Common mistake", "Ignorer une menace lente parce qu’elle ne donne pas échec laisse parfois l’adversaire améliorer toute sa position sans contre-jeu.", "Ignoring a slow threat because it is not check can let the opponent improve the whole position without counterplay.", [["Transfert", "Transfer", "Opposez une menace positionnelle par une action concrète, pas par une inquiétude vague.", "Answer a positional threat with a concrete action, not vague concern."]]),
    ], [
      { title: text("Horizon", "Horizon"), text: text("Regardez quelques coups plus loin que l’attaque immédiate.", "Look a few moves beyond the immediate attack.") },
      { title: text("Case", "Square"), text: text("Une case forte peut être la vraie cible.", "A strong square may be the real target.") },
      { title: text("Prévention", "Prevention"), text: text("Créez du contre-jeu avant que le plan soit mûr.", "Create counterplay before the plan matures.") },
    ], [
      ["4k3/8/8/8/8/8/1N6/4K3 w - - 0 1", "b2", "c4", "Cc4", "Installez la pièce sur une case forte.", "Establish the piece on a strong square.", "La menace positionnelle est l’activité durable gagnée par le cavalier central.", "The positional threat is the lasting activity gained by the centralized knight."],
      ["4k3/8/8/8/8/8/1N6/4K3 w - - 0 1", "b2", "d3", "Cd3", "Préparez une amélioration durable.", "Prepare a lasting improvement.", "Le bon coup ne gagne pas forcément maintenant, mais rend le plan suivant plus fort.", "The right move may not win now, but makes the next plan stronger."],
      ["4k3/8/8/8/8/8/1N6/4K3 w - - 0 1", "b2", "a4", "Na4", "Créez une menace de case et de coordination.", "Create a square and coordination threat.", "Une menace positionnelle devient utile quand elle réduit les bonnes cases adverses.", "A positional threat becomes useful when it reduces the opponent’s good squares."],
    ],
  )),
  "33": topic(tactical(
    "33", text("La menace tactique", "The tactical threat"), text("Une combinaison se prépare avant de frapper.", "A combination is prepared before it strikes."), text("Repérer une menace tactique : une combinaison concrète de coups forcing qui gagne du matériel, donne mat ou transforme la position.", "Spot a tactical threat: a concrete combination of forcing moves that wins material, checkmates or transforms the position."), text("Quel motif se prépare si je ne change pas la géométrie ?", "Which pattern is being prepared if I do not change the geometry?"), text("La menace tactique repose sur une séquence calculable et souvent courte. Elle se distingue d’un simple plan par l’existence d’une conséquence concrète.", "A tactical threat relies on a calculable and often short sequence. It differs from a simple plan because it has a concrete consequence."), [
      section("Définition", "Definition", "Une menace tactique prépare une fourchette, un clouage, une découverte, une prise gagnante ou un mat. Elle existe avant que le motif final ne soit joué.", "A tactical threat prepares a fork, pin, discovery, winning capture or mate. It exists before the final pattern is played.", [["Préparation", "Preparation", "Le coup préparatoire peut attaquer une case, déplacer un défenseur ou ouvrir une ligne.", "The preparatory move may attack a square, move a defender or open a line."]]),
      section("Mécanisme", "Mechanism", "La géométrie de la position rend la combinaison possible au prochain coup. La défense doit donc supprimer le motif ou créer un contre-temps.", "The position’s geometry makes the combination possible next move. The defense must remove the pattern or create a counter-tempo.", [["Forcing", "Forcing", "La menace devient tactique quand la réponse adverse est limitée par la force des coups.", "The threat becomes tactical when the opponent’s reply is limited by forcing moves."]]),
      section("Méthode de détection", "Detection method", "Cherchez les cases de fourchette, les batteries, les défenseurs uniques et les lignes qui vont s’ouvrir. Faites ensuite un coup candidat pour l’adversaire.", "Look for fork squares, batteries, unique defenders and lines about to open. Then make a candidate move for the opponent.", [["Anticiper", "Anticipate", "Avant de jouer, demandez quelle combinaison votre dernier coup a autorisée.", "Before moving, ask which combination your last move allowed."]]),
      section("Erreur fréquente", "Common mistake", "Une menace tactique peut être abandonnée si l’adversaire gagne un tempo par échec ou par attaque de la dame.", "A tactical threat can be abandoned if the opponent gains a tempo with check or a queen attack.", [["Transfert", "Transfer", "Une tactique n’existe jamais hors du tempo : vérifiez qui joue le prochain coup forcing.", "A tactic never exists outside tempo: check who has the next forcing move."]]),
    ], [
      { title: text("Préparer", "Prepare"), text: text("Repérez la combinaison avant son exécution.", "Spot the combination before it is executed.") },
      { title: text("Forcer", "Force"), text: text("Mesurez les réponses disponibles.", "Measure the available replies.") },
      { title: text("Empêcher", "Prevent"), text: text("Retirez le motif ou créez un contre-tempo.", "Remove the pattern or create a counter-tempo.") },
    ], [
      ["k7/8/2r5/8/2N5/8/8/4K3 w - - 0 1", "c4", "e5", "Ne5", "Préparez la fourchette sur deux cibles.", "Prepare the fork against two targets.", "La menace tactique est visible avant même que le gain matériel soit réalisé.", "The tactical threat is visible before the material win is completed."],
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "g3", "Fg3", "Préparez une attaque à la découverte.", "Prepare a discovered attack.", "Le déplacement ouvre une ligne et transforme la batterie en menace concrète.", "The move opens a line and turns the battery into a concrete threat."],
      ["7k/5Q2/6K1/8/8/8/8/8 w - - 0 1", "f7", "g7", "Dg7#", "Exécutez la menace de mat.", "Execute the mating threat.", "La menace préparée devient une combinaison dès que la case critique est disponible.", "The prepared threat becomes a combination once the critical square is available."],
    ],
  )),
  "34": topic(tactical(
    "34", text("La menace latente", "The latent threat"), text("Une possibilité existe déjà, même si personne ne la joue encore.", "A possibility already exists, even if no one has played it yet."), text("Détecter une menace latente : une ressource cachée dans la position qui devient active après un changement de ligne, de défense ou de structure.", "Detect a latent threat: a hidden resource in the position that becomes active after a change of line, defense or structure."), text("Quelle ressource est déjà présente mais attend une condition pour apparaître ?", "Which resource is already present but waiting for a condition to appear?"), text("Une menace latente n’est pas toujours annoncée par une attaque immédiate. Elle repose sur une tension, une batterie, une promotion ou une faiblesse qui peut se révéler.", "A latent threat is not always announced by an immediate attack. It relies on tension, a battery, promotion or a weakness that may be revealed."), [
      section("Définition", "Definition", "La menace latente est une possibilité dormante : une diagonale qui s’ouvrira, un pion qui avancera avec tempo ou une pièce qui deviendra active après un échange.", "A latent threat is a dormant possibility: a diagonal that will open, a pawn that will advance with tempo or a piece that will become active after an exchange.", [["Dormante", "Dormant", "Elle existe dans la géométrie, mais sa réalisation dépend d’une condition.", "It exists in the geometry, but its realization depends on a condition."]]),
      section("Mécanisme", "Mechanism", "Un changement de structure, un déplacement de défenseur ou une ouverture de ligne transforme la ressource latente en menace immédiate.", "A structural change, defender move or opened line turns the latent resource into an immediate threat.", [["Déclencheur", "Trigger", "Le déclencheur peut être votre coup ou une erreur adverse.", "The trigger may be your move or an opponent’s mistake."]]),
      section("Méthode de détection", "Detection method", "Regardez les lignes bloquées, les pions passés potentiels, les pièces alignées et les cases de rupture. Demandez quelle seule modification suffirait à activer la tactique.", "Look at blocked lines, potential passed pawns, aligned pieces and break squares. Ask what single change would activate the tactic.", [["Prévention", "Prevention", "Contrôler la condition d’activation suffit parfois à neutraliser la menace.", "Controlling the activation condition can sometimes neutralize the threat."]]),
      section("Erreur fréquente", "Common mistake", "Une menace latente n’est pas une combinaison garantie. Elle peut perdre sa force si l’adversaire change la structure ou gagne un tempo.", "A latent threat is not a guaranteed combination. It can lose force if the opponent changes the structure or gains a tempo.", [["Transfert", "Transfer", "Apprenez à distinguer la possibilité réelle de l’imagination tactique.", "Learn to distinguish a real possibility from tactical imagination."]]),
    ], [
      { title: text("Condition", "Condition"), text: text("Nommer ce qui doit changer pour activer le motif.", "Name what must change to activate the pattern.") },
      { title: text("Surveillance", "Watch"), text: text("Suivre la ligne, la défense et la structure.", "Track the line, defense and structure.") },
      { title: text("Déclenchement", "Trigger"), text: text("Jouer lorsque la condition devient favorable.", "Play when the condition becomes favorable.") },
    ], [
      ["4k3/8/8/8/8/8/8/R3B1K1 w - - 0 1", "e1", "g3", "Fg3", "Activez la ressource latente de la tour.", "Activate the rook’s latent resource.", "La ligne existe déjà : le déplacement de la pièce avant la rend visible et immédiate.", "The line already exists: moving the front piece makes it visible and immediate."],
      ["4k3/8/8/8/8/8/8/R2N2K1 w - - 0 1", "d1", "f2", "Cf2", "Déclenchez la menace cachée de la batterie.", "Trigger the battery’s hidden threat.", "La menace latente dépendait de la case libre ; une fois libérée, l’attaque devient concrète.", "The latent threat depended on an open square; once cleared, the attack becomes concrete."],
      ["7k/5Q2/6K1/8/8/8/8/8 w - - 0 1", "f7", "g7", "Dg7#", "Réalisez la menace latente de mat.", "Realize the latent mating threat.", "La pression sur les cases de fuite existait déjà et devient mat lorsque la case critique est jouée.", "Pressure on the escape squares already existed and becomes mate when the critical square is used."],
    ],
  )),
};


// Les positions interactives sont maintenues dans un module dédié afin de pouvoir
// les auditer indépendamment de la théorie longue de chaque leçon.
for (const [lessonKey, specs] of Object.entries(correctedTacticalSteps)) {
  const lesson = levelTwoLessons[lessonKey];
  if (!lesson) continue;
  const steps = specs.map(step);
  lesson.startingFen = steps[0]?.positionFen ?? lesson.startingFen;
  lesson.steps = steps;
}
